import { Career } from '@/types';

export const careers: Career[] = [
  {
    id: '1',
    name: 'UX Designer',
    cluster: 'Design & Creative',
    description: 'Design digital experiences that millions of people use daily. Combine psychology, art, and technology to make apps and websites intuitive and delightful.',
    skills: ['Visual Design', 'User Research', 'Prototyping', 'Figma', 'Empathy', 'Communication'],
    salary_range: { min: 500000, max: 2500000, currency: 'INR' },
    ai_risk_score: 25,
    growth_trend: 'rising',
    education_path: 'Design degree, BFA, or self-taught with portfolio. Bootcamps available.',
    day_in_life: 'Talk to users, sketch wireframes, create prototypes in Figma, present designs to teams, iterate based on feedback.',
    icon: '🎨',
    identity_match: { creative: 90, analytical: 50, social: 70, practical: 60, entrepreneurial: 40, caring: 80 }
  },
  {
    id: '2',
    name: 'Data Scientist',
    cluster: 'Technology & AI',
    description: 'Extract insights from massive datasets to help companies make better decisions. Use statistics, programming, and machine learning.',
    skills: ['Python', 'Statistics', 'Machine Learning', 'SQL', 'Data Visualization', 'Critical Thinking'],
    salary_range: { min: 800000, max: 4000000, currency: 'INR' },
    ai_risk_score: 35,
    growth_trend: 'rising',
    education_path: 'BTech/BSc in CS, Statistics, or Math. Masters preferred. Online courses available.',
    day_in_life: 'Clean and analyze datasets, build ML models, create dashboards, present findings to stakeholders.',
    icon: '📊',
    identity_match: { creative: 40, analytical: 95, social: 30, practical: 70, entrepreneurial: 50, caring: 20 }
  },
  {
    id: '3',
    name: 'Clinical Psychologist',
    cluster: 'Healthcare & Wellness',
    description: 'Help people understand their minds, overcome mental health challenges, and live more fulfilling lives through therapy and assessment.',
    skills: ['Active Listening', 'Empathy', 'Research', 'Assessment', 'Communication', 'Patience'],
    salary_range: { min: 400000, max: 1800000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'rising',
    education_path: 'BA/BSc Psychology → MA/MSc Clinical Psychology → MPhil (RCI license). 7-8 years.',
    day_in_life: 'Conduct therapy sessions, administer psychological tests, write case notes, attend supervision, read research.',
    icon: '🧠',
    identity_match: { creative: 30, analytical: 60, social: 90, practical: 40, entrepreneurial: 30, caring: 95 }
  },
  {
    id: '4',
    name: 'Product Manager',
    cluster: 'Business & Strategy',
    description: 'Define what products to build and why. Bridge between engineering, design, and business. The CEO of the product.',
    skills: ['Strategy', 'Communication', 'Data Analysis', 'User Empathy', 'Prioritization', 'Leadership'],
    salary_range: { min: 1000000, max: 5000000, currency: 'INR' },
    ai_risk_score: 20,
    growth_trend: 'rising',
    education_path: 'Any degree + tech understanding. MBA or engineering background common. Experience matters most.',
    day_in_life: 'Prioritize features, talk to customers, analyze metrics, write product specs, coordinate with engineering and design teams.',
    icon: '🚀',
    identity_match: { creative: 60, analytical: 70, social: 80, practical: 50, entrepreneurial: 85, caring: 40 }
  },
  {
    id: '5',
    name: 'Environmental Scientist',
    cluster: 'Science & Research',
    description: 'Study and protect the environment. Work on climate change, pollution, conservation, and sustainable development.',
    skills: ['Research', 'Data Analysis', 'Fieldwork', 'Report Writing', 'GIS', 'Environmental Law'],
    salary_range: { min: 400000, max: 1500000, currency: 'INR' },
    ai_risk_score: 15,
    growth_trend: 'rising',
    education_path: 'BSc Environmental Science → MSc/MTech. PhD for research roles.',
    day_in_life: 'Collect field samples, analyze environmental data, write impact reports, advise on regulations, present to stakeholders.',
    icon: '🌍',
    identity_match: { creative: 30, analytical: 80, social: 40, practical: 70, entrepreneurial: 30, caring: 90 }
  },
  {
    id: '6',
    name: 'Content Creator / YouTuber',
    cluster: 'Media & Entertainment',
    description: 'Create videos, podcasts, or written content that educates, entertains, or inspires audiences. Build a personal brand.',
    skills: ['Storytelling', 'Video Editing', 'Social Media', 'Public Speaking', 'Marketing', 'Consistency'],
    salary_range: { min: 200000, max: 10000000, currency: 'INR' },
    ai_risk_score: 30,
    growth_trend: 'rising',
    education_path: 'No formal degree required. Mass Communication, Film, or self-taught. Portfolio is everything.',
    day_in_life: 'Script content, shoot videos, edit footage, engage with audience, analyze metrics, collaborate with brands.',
    icon: '🎬',
    identity_match: { creative: 95, analytical: 30, social: 85, practical: 40, entrepreneurial: 90, caring: 50 }
  },
  {
    id: '7',
    name: 'Chartered Accountant',
    cluster: 'Finance & Commerce',
    description: 'Audit companies, manage taxes, advise on financial strategy. One of India\'s most respected and stable professions.',
    skills: ['Accounting', 'Tax Law', 'Auditing', 'Financial Analysis', 'Attention to Detail', 'Excel'],
    salary_range: { min: 700000, max: 3000000, currency: 'INR' },
    ai_risk_score: 45,
    growth_trend: 'stable',
    education_path: 'After Class 12: CA Foundation → Intermediate → Final (3-5 years). Articleship required.',
    day_in_life: 'Review financial statements, file tax returns, audit companies, advise clients, stay updated on regulations.',
    icon: '📈',
    identity_match: { creative: 10, analytical: 95, social: 40, practical: 80, entrepreneurial: 50, caring: 20 }
  },
  {
    id: '8',
    name: 'Game Developer',
    cluster: 'Technology & AI',
    description: 'Build video games — from mobile games to AAA titles. Combine programming, art, storytelling, and physics.',
    skills: ['C++/C#', 'Unity/Unreal', '3D Math', 'Game Design', 'Problem Solving', 'Creativity'],
    salary_range: { min: 500000, max: 3000000, currency: 'INR' },
    ai_risk_score: 30,
    growth_trend: 'rising',
    education_path: 'BTech CS, BCA, or game design programs. Self-taught with portfolio works too.',
    day_in_life: 'Code game mechanics, design levels, fix bugs, playtest, collaborate with artists and sound designers.',
    icon: '🎮',
    identity_match: { creative: 90, analytical: 80, social: 30, practical: 60, entrepreneurial: 50, caring: 10 }
  },
  {
    id: '9',
    name: 'Civil Services (IAS/IPS/IFS)',
    cluster: 'Government & Public Policy',
    description: 'Lead government administration, shape policy, manage districts. One of the most powerful and competitive careers in India.',
    skills: ['General Knowledge', 'Writing', 'Decision Making', 'Leadership', 'Ethics', 'Stamina'],
    salary_range: { min: 800000, max: 2500000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'stable',
    education_path: 'Any graduation → UPSC CSE (1-3 year prep typical). Success rate <1%.',
    day_in_life: 'Varies by posting: manage district administration, implement government schemes, handle crises, meet citizens.',
    icon: '🏛️',
    identity_match: { creative: 20, analytical: 60, social: 70, practical: 50, entrepreneurial: 30, caring: 80 }
  },
  {
    id: '10',
    name: 'Architect',
    cluster: 'Design & Creative',
    description: 'Design buildings, spaces, and cities. Combine art, engineering, and environmental awareness to shape the built world.',
    skills: ['Design Thinking', 'AutoCAD/Revit', 'Mathematics', 'Physics', 'Model Making', 'Visualization'],
    salary_range: { min: 400000, max: 2000000, currency: 'INR' },
    ai_risk_score: 25,
    growth_trend: 'stable',
    education_path: 'BArch (5 years) after Class 12 with Math. NATA entrance exam.',
    day_in_life: 'Design buildings in CAD software, visit construction sites, meet clients, prepare blueprints, coordinate with engineers.',
    icon: '🏗️',
    identity_match: { creative: 90, analytical: 70, social: 50, practical: 80, entrepreneurial: 40, caring: 30 }
  },
  {
    id: '11',
    name: 'AI/ML Engineer',
    cluster: 'Technology & AI',
    description: 'Build intelligent systems that can learn, reason, and make decisions. The hottest career in tech right now.',
    skills: ['Python', 'Deep Learning', 'Mathematics', 'TensorFlow/PyTorch', 'Problem Solving', 'Research'],
    salary_range: { min: 1000000, max: 6000000, currency: 'INR' },
    ai_risk_score: 15,
    growth_trend: 'rising',
    education_path: 'BTech/BSc CS or Math → specialize in ML. Masters/PhD valued. Online courses available.',
    day_in_life: 'Train ML models, process data, read research papers, experiment with architectures, deploy models to production.',
    icon: '🤖',
    identity_match: { creative: 50, analytical: 95, social: 20, practical: 60, entrepreneurial: 60, caring: 10 }
  },
  {
    id: '12',
    name: 'Doctor (MBBS)',
    cluster: 'Healthcare & Wellness',
    description: 'Diagnose and treat illnesses, save lives. One of India\'s most respected careers with deep human impact.',
    skills: ['Biology', 'Chemistry', 'Empathy', 'Decision Making', 'Stamina', 'Communication'],
    salary_range: { min: 600000, max: 3000000, currency: 'INR' },
    ai_risk_score: 15,
    growth_trend: 'stable',
    education_path: 'Class 12 PCB → NEET → MBBS (5.5 years) → MD/MS specialization (3 years).',
    day_in_life: 'See patients in OPD, conduct rounds in wards, perform procedures, read reports, attend emergencies.',
    icon: '⚕️',
    identity_match: { creative: 20, analytical: 70, social: 60, practical: 80, entrepreneurial: 30, caring: 95 }
  },
  {
    id: '13',
    name: 'Graphic Designer',
    cluster: 'Design & Creative',
    description: 'Create visual content — logos, posters, social media, packaging. Turn ideas into stunning visuals.',
    skills: ['Adobe Suite', 'Typography', 'Color Theory', 'Branding', 'Creativity', 'Client Communication'],
    salary_range: { min: 300000, max: 1500000, currency: 'INR' },
    ai_risk_score: 50,
    growth_trend: 'stable',
    education_path: 'BDes, BFA, or self-taught. Portfolio matters more than degree.',
    day_in_life: 'Brief with clients, create concepts, design in Adobe/Figma, iterate on feedback, prepare files for print/digital.',
    icon: '✏️',
    identity_match: { creative: 95, analytical: 30, social: 50, practical: 60, entrepreneurial: 50, caring: 20 }
  },
  {
    id: '14',
    name: 'Lawyer',
    cluster: 'Law & Governance',
    description: 'Argue cases in court, draft contracts, advise on legal matters. Fight for justice and protect rights.',
    skills: ['Legal Research', 'Argumentation', 'Writing', 'Critical Thinking', 'Public Speaking', 'Ethics'],
    salary_range: { min: 400000, max: 3000000, currency: 'INR' },
    ai_risk_score: 30,
    growth_trend: 'stable',
    education_path: '5-year LLB after Class 12 (CLAT exam) or 3-year LLB after graduation.',
    day_in_life: 'Research case law, draft petitions, argue in court, meet clients, negotiate settlements.',
    icon: '⚖️',
    identity_match: { creative: 30, analytical: 80, social: 80, practical: 50, entrepreneurial: 40, caring: 60 }
  },
  {
    id: '15',
    name: 'Entrepreneur / Startup Founder',
    cluster: 'Business & Strategy',
    description: 'Build your own company from scratch. Solve real problems, create jobs, and potentially change the world.',
    skills: ['Leadership', 'Sales', 'Product Thinking', 'Resilience', 'Networking', 'Financial Literacy'],
    salary_range: { min: 0, max: 100000000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'rising',
    education_path: 'Any degree or none. MBA helpful but not required. Real-world experience is key.',
    day_in_life: 'Set vision and strategy, talk to customers, recruit team, pitch to investors, solve problems, manage chaos.',
    icon: '💡',
    identity_match: { creative: 70, analytical: 50, social: 80, practical: 60, entrepreneurial: 99, caring: 40 }
  },
  {
    id: '16',
    name: 'Journalist',
    cluster: 'Media & Entertainment',
    description: 'Investigate stories, report news, hold power accountable. Tell the stories that matter.',
    skills: ['Writing', 'Research', 'Interviewing', 'Ethics', 'Digital Media', 'Curiosity'],
    salary_range: { min: 300000, max: 1500000, currency: 'INR' },
    ai_risk_score: 40,
    growth_trend: 'declining',
    education_path: 'BA Journalism/Mass Communication. English or regional language skills essential.',
    day_in_life: 'Chase leads, interview sources, write/edit stories, attend press briefings, manage social media presence.',
    icon: '📰',
    identity_match: { creative: 70, analytical: 60, social: 90, practical: 40, entrepreneurial: 40, caring: 70 }
  },
  {
    id: '17',
    name: 'Cybersecurity Analyst',
    cluster: 'Technology & AI',
    description: 'Protect organizations from hackers and cyber attacks. Guard data, networks, and digital infrastructure.',
    skills: ['Networking', 'Linux', 'Python', 'Threat Analysis', 'Ethical Hacking', 'Problem Solving'],
    salary_range: { min: 600000, max: 3500000, currency: 'INR' },
    ai_risk_score: 15,
    growth_trend: 'rising',
    education_path: 'BTech CS/IT → certifications (CEH, CISSP). Specialization through practice.',
    day_in_life: 'Monitor network traffic, investigate security incidents, conduct penetration tests, update security policies.',
    icon: '🔒',
    identity_match: { creative: 40, analytical: 90, social: 20, practical: 80, entrepreneurial: 30, caring: 30 }
  },
  {
    id: '18',
    name: 'Social Worker / NGO Professional',
    cluster: 'Social Impact',
    description: 'Work with communities to solve social problems — poverty, education, health, gender, environment.',
    skills: ['Empathy', 'Community Building', 'Project Management', 'Fundraising', 'Communication', 'Resilience'],
    salary_range: { min: 250000, max: 1200000, currency: 'INR' },
    ai_risk_score: 5,
    growth_trend: 'stable',
    education_path: 'BSW or MSW (Social Work). Development studies or public policy degrees also work.',
    day_in_life: 'Visit communities, run programs, write reports, manage volunteers, raise funds, advocate for change.',
    icon: '🤝',
    identity_match: { creative: 30, analytical: 40, social: 90, practical: 60, entrepreneurial: 40, caring: 99 }
  },
  {
    id: '19',
    name: 'Fashion Designer',
    cluster: 'Design & Creative',
    description: 'Design clothing, accessories, and fashion collections. Blend art, culture, and business.',
    skills: ['Sketching', 'Pattern Making', 'Fabric Knowledge', 'Trend Analysis', 'Branding', 'Sewing'],
    salary_range: { min: 300000, max: 2000000, currency: 'INR' },
    ai_risk_score: 30,
    growth_trend: 'stable',
    education_path: 'BDes Fashion from NIFT/NID/Pearl. 4-year programs with portfolio admission.',
    day_in_life: 'Sketch designs, select fabrics, supervise production, attend fashion shows, meet buyers and brands.',
    icon: '👗',
    identity_match: { creative: 99, analytical: 20, social: 60, practical: 70, entrepreneurial: 70, caring: 20 }
  },
  {
    id: '20',
    name: 'Supply Chain Manager',
    cluster: 'Business & Strategy',
    description: 'Manage how products move from factory to customer. Optimize logistics, inventory, and operations.',
    skills: ['Logistics', 'Data Analysis', 'Negotiation', 'ERP Systems', 'Problem Solving', 'Planning'],
    salary_range: { min: 600000, max: 2500000, currency: 'INR' },
    ai_risk_score: 40,
    growth_trend: 'rising',
    education_path: 'Engineering/Commerce + MBA (Operations). Supply chain certifications help.',
    day_in_life: 'Track shipments, negotiate with vendors, optimize warehouse operations, analyze demand forecasts.',
    icon: '📦',
    identity_match: { creative: 20, analytical: 80, social: 50, practical: 90, entrepreneurial: 40, caring: 10 }
  },
  {
    id: '21',
    name: 'Physiotherapist',
    cluster: 'Healthcare & Wellness',
    description: 'Help people recover from injuries and disabilities through exercise, massage, and movement therapy.',
    skills: ['Anatomy', 'Exercise Science', 'Manual Therapy', 'Empathy', 'Patience', 'Communication'],
    salary_range: { min: 350000, max: 1500000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'rising',
    education_path: 'BPT (4.5 years) after Class 12 with PCB. MPT for specialization.',
    day_in_life: 'Assess patients, design exercise programs, perform manual therapy, track recovery progress.',
    icon: '💪',
    identity_match: { creative: 20, analytical: 50, social: 70, practical: 90, entrepreneurial: 40, caring: 90 }
  },
  {
    id: '22',
    name: 'Film Director',
    cluster: 'Media & Entertainment',
    description: 'Bring stories to life on screen. Lead creative vision for films, web series, and ads.',
    skills: ['Storytelling', 'Visual Thinking', 'Leadership', 'Editing', 'Communication', 'Persistence'],
    salary_range: { min: 200000, max: 5000000, currency: 'INR' },
    ai_risk_score: 15,
    growth_trend: 'rising',
    education_path: 'Film school (FTII, Whistling Woods) or assistant director route. No fixed path.',
    day_in_life: 'Develop scripts, plan shots, direct actors on set, oversee editing, collaborate with crew.',
    icon: '🎥',
    identity_match: { creative: 99, analytical: 30, social: 70, practical: 40, entrepreneurial: 60, caring: 30 }
  },
  {
    id: '23',
    name: 'Robotics Engineer',
    cluster: 'Technology & AI',
    description: 'Design and build robots for manufacturing, healthcare, exploration, and everyday life.',
    skills: ['Mechanical Engineering', 'Electronics', 'Programming', 'Control Systems', 'CAD', 'Problem Solving'],
    salary_range: { min: 600000, max: 2500000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'rising',
    education_path: 'BTech Mechanical/Electronics/Robotics. MTech or MS for research roles.',
    day_in_life: 'Design robot mechanisms, program controllers, test prototypes, troubleshoot hardware, read research.',
    icon: '🦾',
    identity_match: { creative: 60, analytical: 90, social: 20, practical: 95, entrepreneurial: 50, caring: 10 }
  },
  {
    id: '24',
    name: 'Digital Marketing Manager',
    cluster: 'Business & Strategy',
    description: 'Grow brands online through SEO, social media, ads, and content. Data-driven creativity.',
    skills: ['SEO/SEM', 'Social Media', 'Analytics', 'Content Strategy', 'Copywriting', 'A/B Testing'],
    salary_range: { min: 400000, max: 2000000, currency: 'INR' },
    ai_risk_score: 45,
    growth_trend: 'stable',
    education_path: 'Any degree + digital marketing certifications. MBA Marketing is a plus.',
    day_in_life: 'Plan campaigns, analyze ad performance, create content calendars, manage social channels, optimize conversion funnels.',
    icon: '📱',
    identity_match: { creative: 70, analytical: 60, social: 70, practical: 50, entrepreneurial: 70, caring: 20 }
  },
  {
    id: '25',
    name: 'Sports Coach / Fitness Trainer',
    cluster: 'Sports & Fitness',
    description: 'Train athletes or help people get fit. Combine exercise science, motivation, and discipline.',
    skills: ['Exercise Science', 'Nutrition', 'Motivation', 'Anatomy', 'Communication', 'Patience'],
    salary_range: { min: 300000, max: 1500000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'rising',
    education_path: 'BPEd, BSc Sports Science, or certified personal training (ACE, NSCA).',
    day_in_life: 'Design workout programs, train clients, track progress, learn new techniques, manage nutrition plans.',
    icon: '🏋️',
    identity_match: { creative: 20, analytical: 40, social: 80, practical: 90, entrepreneurial: 50, caring: 70 }
  },
  {
    id: '26',
    name: 'Biotechnologist',
    cluster: 'Science & Research',
    description: 'Use biology and technology to develop medicines, crops, and industrial solutions.',
    skills: ['Biology', 'Lab Techniques', 'Research', 'Data Analysis', 'Scientific Writing', 'Problem Solving'],
    salary_range: { min: 400000, max: 1800000, currency: 'INR' },
    ai_risk_score: 20,
    growth_trend: 'rising',
    education_path: 'BTech/BSc Biotechnology → MSc/MTech → PhD for research. GATE exam for higher studies.',
    day_in_life: 'Run experiments in the lab, analyze results, write research papers, attend conferences, collaborate with teams.',
    icon: '🧬',
    identity_match: { creative: 40, analytical: 90, social: 30, practical: 70, entrepreneurial: 40, caring: 50 }
  },
  {
    id: '27',
    name: 'Chef / Culinary Professional',
    cluster: 'Hospitality & Food',
    description: 'Create food experiences — from fine dining to street food innovation. Combine creativity, science, and culture.',
    skills: ['Cooking Techniques', 'Flavor Pairing', 'Kitchen Management', 'Food Safety', 'Creativity', 'Stamina'],
    salary_range: { min: 250000, max: 1500000, currency: 'INR' },
    ai_risk_score: 5,
    growth_trend: 'rising',
    education_path: 'Hotel Management (IHM) or culinary school. Apprenticeships under known chefs.',
    day_in_life: 'Plan menus, prep ingredients, cook during service, manage kitchen staff, experiment with new dishes.',
    icon: '👨‍🍳',
    identity_match: { creative: 90, analytical: 30, social: 50, practical: 95, entrepreneurial: 60, caring: 40 }
  },
  {
    id: '28',
    name: 'Teacher / Educator',
    cluster: 'Education',
    description: 'Shape young minds and inspire the next generation. One of the most impactful careers that exists.',
    skills: ['Communication', 'Patience', 'Subject Expertise', 'Classroom Management', 'Empathy', 'Creativity'],
    salary_range: { min: 300000, max: 1200000, currency: 'INR' },
    ai_risk_score: 20,
    growth_trend: 'stable',
    education_path: 'Subject degree + BEd. NET/SET for college teaching. PhD for university positions.',
    day_in_life: 'Prepare lessons, teach classes, grade assignments, mentor students, attend parent meetings, update curriculum.',
    icon: '📚',
    identity_match: { creative: 50, analytical: 50, social: 90, practical: 40, entrepreneurial: 20, caring: 95 }
  },
  {
    id: '29',
    name: 'Investment Banker',
    cluster: 'Finance & Commerce',
    description: 'Advise companies on mergers, acquisitions, and fundraising. High-pressure, high-reward finance career.',
    skills: ['Financial Modeling', 'Excel', 'Valuation', 'Presentation', 'Networking', 'Endurance'],
    salary_range: { min: 1200000, max: 8000000, currency: 'INR' },
    ai_risk_score: 35,
    growth_trend: 'stable',
    education_path: 'Top engineering/commerce degree → MBA from IIM/ISB/global school. CFA is a plus.',
    day_in_life: 'Build financial models, create pitch decks, attend client meetings, work on deal execution, long hours.',
    icon: '💰',
    identity_match: { creative: 20, analytical: 90, social: 60, practical: 50, entrepreneurial: 70, caring: 10 }
  },
  {
    id: '30',
    name: 'Interior Designer',
    cluster: 'Design & Creative',
    description: 'Transform spaces — homes, offices, restaurants, hotels. Make spaces beautiful, functional, and meaningful.',
    skills: ['Space Planning', 'Color Theory', 'AutoCAD/SketchUp', 'Material Knowledge', 'Client Management', 'Creativity'],
    salary_range: { min: 350000, max: 1800000, currency: 'INR' },
    ai_risk_score: 25,
    growth_trend: 'rising',
    education_path: 'BDes Interior Design (4 years) or diploma programs. Portfolio is essential.',
    day_in_life: 'Meet clients, create mood boards, draft floor plans, select materials, supervise installations.',
    icon: '🏠',
    identity_match: { creative: 90, analytical: 40, social: 60, practical: 80, entrepreneurial: 60, caring: 30 }
  },
  {
    id: '31',
    name: 'Mechanical Engineer',
    cluster: 'Engineering',
    description: 'Design and build machines, engines, and mechanical systems. From cars to spacecraft.',
    skills: ['Physics', 'CAD/CAM', 'Thermodynamics', 'Manufacturing', 'Problem Solving', 'Mathematics'],
    salary_range: { min: 400000, max: 2000000, currency: 'INR' },
    ai_risk_score: 35,
    growth_trend: 'stable',
    education_path: 'BTech Mechanical Engineering (4 years). JEE/state entrance exams.',
    day_in_life: 'Design parts in CAD, run simulations, visit manufacturing floors, review quality, solve technical problems.',
    icon: '⚙️',
    identity_match: { creative: 40, analytical: 85, social: 20, practical: 95, entrepreneurial: 30, caring: 10 }
  },
  {
    id: '32',
    name: 'Musician / Music Producer',
    cluster: 'Arts & Performance',
    description: 'Create, perform, and produce music. From classical to electronic, Bollywood to indie.',
    skills: ['Musical Instrument/Vocals', 'Music Theory', 'DAW Software', 'Ear Training', 'Creativity', 'Discipline'],
    salary_range: { min: 200000, max: 5000000, currency: 'INR' },
    ai_risk_score: 20,
    growth_trend: 'rising',
    education_path: 'Music academy, university music program, or self-taught. Talent + practice + networking.',
    day_in_life: 'Practice instrument, compose/produce tracks, perform at gigs, collaborate with artists, market music online.',
    icon: '🎵',
    identity_match: { creative: 99, analytical: 40, social: 60, practical: 30, entrepreneurial: 50, caring: 30 }
  },
  {
    id: '33',
    name: 'Pharmacist',
    cluster: 'Healthcare & Wellness',
    description: 'Dispense medicines, advise on drug interactions, ensure safe medication use. Bridge between doctors and patients.',
    skills: ['Pharmacology', 'Chemistry', 'Patient Counseling', 'Attention to Detail', 'Regulations', 'Communication'],
    salary_range: { min: 300000, max: 1200000, currency: 'INR' },
    ai_risk_score: 40,
    growth_trend: 'stable',
    education_path: 'BPharm (4 years) or DPharm (2 years) after Class 12 with PCB/PCM.',
    day_in_life: 'Dispense prescriptions, counsel patients, manage inventory, check drug interactions, stay updated on new drugs.',
    icon: '💊',
    identity_match: { creative: 10, analytical: 70, social: 50, practical: 80, entrepreneurial: 40, caring: 70 }
  },
  {
    id: '34',
    name: 'Ethical Hacker / Penetration Tester',
    cluster: 'Technology & AI',
    description: 'Hack into systems legally to find vulnerabilities before the bad guys do. Defend the digital world.',
    skills: ['Networking', 'Python', 'Linux', 'Web Security', 'Reverse Engineering', 'Creative Problem Solving'],
    salary_range: { min: 500000, max: 3000000, currency: 'INR' },
    ai_risk_score: 15,
    growth_trend: 'rising',
    education_path: 'BTech CS/IT + CEH, OSCP certifications. Bug bounty experience valued.',
    day_in_life: 'Scan networks for vulnerabilities, attempt controlled exploits, document findings, recommend fixes, write reports.',
    icon: '🕵️',
    identity_match: { creative: 60, analytical: 90, social: 10, practical: 70, entrepreneurial: 40, caring: 20 }
  },
  {
    id: '35',
    name: 'Psychologist (Organizational/Industrial)',
    cluster: 'Business & Strategy',
    description: 'Apply psychology to workplaces — hiring, team dynamics, leadership, culture, and employee well-being.',
    skills: ['Psychology', 'Assessment Design', 'Data Analysis', 'Communication', 'Coaching', 'Research'],
    salary_range: { min: 500000, max: 2000000, currency: 'INR' },
    ai_risk_score: 20,
    growth_trend: 'rising',
    education_path: 'BA/BSc Psychology → MA I/O Psychology. MBA-Psychology combo is powerful.',
    day_in_life: 'Design hiring assessments, conduct employee surveys, coach leaders, analyze engagement data, run workshops.',
    icon: '🎯',
    identity_match: { creative: 40, analytical: 70, social: 80, practical: 50, entrepreneurial: 40, caring: 70 }
  },
  {
    id: '36',
    name: 'Animator / VFX Artist',
    cluster: 'Media & Entertainment',
    description: 'Create animated content and visual effects for films, games, ads, and the metaverse.',
    skills: ['3D Modeling', 'Animation Principles', 'Maya/Blender', 'Compositing', 'Storytelling', 'Patience'],
    salary_range: { min: 300000, max: 1800000, currency: 'INR' },
    ai_risk_score: 40,
    growth_trend: 'rising',
    education_path: 'BDes Animation, diploma programs (Arena, MAAC), or self-taught with strong reel.',
    day_in_life: 'Model 3D characters, animate scenes, add visual effects, render footage, collaborate with directors.',
    icon: '🎭',
    identity_match: { creative: 95, analytical: 50, social: 20, practical: 60, entrepreneurial: 30, caring: 10 }
  },
  {
    id: '37',
    name: 'Civil Engineer',
    cluster: 'Engineering',
    description: 'Design and build infrastructure — roads, bridges, buildings, dams. Shape the physical world.',
    skills: ['Structural Analysis', 'AutoCAD', 'Mathematics', 'Project Management', 'Surveying', 'Physics'],
    salary_range: { min: 400000, max: 1800000, currency: 'INR' },
    ai_risk_score: 30,
    growth_trend: 'stable',
    education_path: 'BTech Civil Engineering (4 years). GATE for higher studies. Site experience essential.',
    day_in_life: 'Design structures, visit construction sites, review blueprints, manage contractors, ensure safety compliance.',
    icon: '🌉',
    identity_match: { creative: 30, analytical: 80, social: 30, practical: 95, entrepreneurial: 30, caring: 20 }
  },
  {
    id: '38',
    name: 'Public Policy Analyst',
    cluster: 'Government & Public Policy',
    description: 'Research and advise on government policies — education, health, economy, environment. Shape how India grows.',
    skills: ['Research', 'Data Analysis', 'Writing', 'Economics', 'Public Speaking', 'Systems Thinking'],
    salary_range: { min: 500000, max: 2000000, currency: 'INR' },
    ai_risk_score: 20,
    growth_trend: 'rising',
    education_path: 'Any degree + MPP/MPA from policy schools (NLSIU, IGIDR, Ashoka, Jindal). PhD for think tanks.',
    day_in_life: 'Analyze data on policy issues, write policy briefs, attend stakeholder meetings, present to policymakers.',
    icon: '📋',
    identity_match: { creative: 30, analytical: 80, social: 60, practical: 40, entrepreneurial: 30, caring: 80 }
  },
  {
    id: '39',
    name: 'Blockchain Developer',
    cluster: 'Technology & AI',
    description: 'Build decentralized applications, smart contracts, and Web3 solutions. The frontier of internet technology.',
    skills: ['Solidity', 'JavaScript', 'Cryptography', 'Smart Contracts', 'Problem Solving', 'Systems Design'],
    salary_range: { min: 800000, max: 4000000, currency: 'INR' },
    ai_risk_score: 25,
    growth_trend: 'rising',
    education_path: 'BTech CS + blockchain certifications. Self-taught with portfolio works. Hackathons help.',
    day_in_life: 'Write smart contracts, audit code for security, build DApps, research new protocols, participate in DAOs.',
    icon: '⛓️',
    identity_match: { creative: 40, analytical: 90, social: 20, practical: 60, entrepreneurial: 70, caring: 10 }
  },
  {
    id: '40',
    name: 'Wildlife Conservationist',
    cluster: 'Science & Research',
    description: 'Protect endangered species and ecosystems. Work in forests, sanctuaries, and research stations.',
    skills: ['Biology', 'Fieldwork', 'GIS/Remote Sensing', 'Research', 'Advocacy', 'Physical Fitness'],
    salary_range: { min: 300000, max: 1200000, currency: 'INR' },
    ai_risk_score: 5,
    growth_trend: 'rising',
    education_path: 'BSc Zoology/Environmental Science → MSc Wildlife Biology. Indian Forest Service is another route.',
    day_in_life: 'Track wildlife populations, set camera traps, analyze data, write conservation plans, work with local communities.',
    icon: '🐅',
    identity_match: { creative: 20, analytical: 60, social: 40, practical: 80, entrepreneurial: 20, caring: 95 }
  },
  {
    id: '41',
    name: 'Airline Pilot',
    cluster: 'Aviation & Transport',
    description: 'Fly commercial aircraft carrying hundreds of passengers. One of the most skilled and well-paid professions.',
    skills: ['Aviation Knowledge', 'Mathematics', 'Decision Making', 'Spatial Awareness', 'Communication', 'Calm Under Pressure'],
    salary_range: { min: 1000000, max: 5000000, currency: 'INR' },
    ai_risk_score: 20,
    growth_trend: 'rising',
    education_path: 'Class 12 with PCM → CPL from flying school (DGCA approved). ~2-3 years training.',
    day_in_life: 'Pre-flight checks, fly aircraft, navigate weather, communicate with ATC, manage crew, simulator training.',
    icon: '✈️',
    identity_match: { creative: 10, analytical: 70, social: 30, practical: 90, entrepreneurial: 20, caring: 30 }
  },
  {
    id: '42',
    name: 'Stand-up Comedian',
    cluster: 'Arts & Performance',
    description: 'Make people laugh through original comedy. Perform at clubs, festivals, and create online content.',
    skills: ['Comedy Writing', 'Stage Presence', 'Timing', 'Observation', 'Resilience', 'Social Media'],
    salary_range: { min: 100000, max: 5000000, currency: 'INR' },
    ai_risk_score: 5,
    growth_trend: 'rising',
    education_path: 'No formal degree. Open mics, comedy workshops, and stage time are the training.',
    day_in_life: 'Write jokes, perform at open mics and shows, watch other comedians, engage on social media, tour.',
    icon: '😂',
    identity_match: { creative: 90, analytical: 40, social: 95, practical: 20, entrepreneurial: 70, caring: 30 }
  },
  {
    id: '43',
    name: 'Climate Tech Engineer',
    cluster: 'Science & Research',
    description: 'Build technology solutions for climate change — renewable energy, carbon capture, sustainable materials.',
    skills: ['Engineering', 'Sustainability', 'Data Analysis', 'Systems Thinking', 'Innovation', 'Project Management'],
    salary_range: { min: 600000, max: 2500000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'rising',
    education_path: 'BTech in Energy/Environmental/Chemical Engineering. Specialized masters programs emerging.',
    day_in_life: 'Design clean energy systems, run pilot projects, analyze environmental impact data, collaborate with policy teams.',
    icon: '🌱',
    identity_match: { creative: 50, analytical: 80, social: 30, practical: 80, entrepreneurial: 50, caring: 90 }
  },
  {
    id: '44',
    name: 'Sports Psychologist',
    cluster: 'Sports & Fitness',
    description: 'Help athletes perform under pressure, recover from setbacks, and build mental resilience.',
    skills: ['Psychology', 'Sports Science', 'Coaching', 'Mindfulness', 'Communication', 'Empathy'],
    salary_range: { min: 400000, max: 1500000, currency: 'INR' },
    ai_risk_score: 5,
    growth_trend: 'rising',
    education_path: 'MA/MSc Psychology → specialization in sports psychology. Certification through ISSP or similar.',
    day_in_life: 'Work with athletes on mental skills, conduct visualization sessions, help with performance anxiety, travel with teams.',
    icon: '🏆',
    identity_match: { creative: 30, analytical: 60, social: 80, practical: 40, entrepreneurial: 30, caring: 85 }
  },
  {
    id: '45',
    name: 'DevOps Engineer',
    cluster: 'Technology & AI',
    description: 'Bridge development and operations. Automate deployments, manage cloud infrastructure, keep systems running.',
    skills: ['Linux', 'Docker/Kubernetes', 'CI/CD', 'AWS/GCP', 'Scripting', 'Monitoring'],
    salary_range: { min: 800000, max: 3500000, currency: 'INR' },
    ai_risk_score: 35,
    growth_trend: 'rising',
    education_path: 'BTech CS/IT. Cloud certifications (AWS, GCP, Azure). 2-3 years experience as developer helps.',
    day_in_life: 'Manage deployments, set up CI/CD pipelines, monitor system health, troubleshoot outages, optimize infrastructure.',
    icon: '☁️',
    identity_match: { creative: 20, analytical: 85, social: 20, practical: 90, entrepreneurial: 30, caring: 10 }
  },
  {
    id: '46',
    name: 'Human Rights Lawyer',
    cluster: 'Law & Governance',
    description: 'Fight for justice — defend civil liberties, fight discrimination, protect the vulnerable through law.',
    skills: ['Constitutional Law', 'Research', 'Advocacy', 'Public Speaking', 'Writing', 'Empathy'],
    salary_range: { min: 300000, max: 1500000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'stable',
    education_path: '5-year LLB (CLAT) → specialize through NGOs, legal aid, or human rights organizations.',
    day_in_life: 'File PILs, represent marginalized communities, research case law, engage with media, attend court.',
    icon: '✊',
    identity_match: { creative: 30, analytical: 70, social: 80, practical: 40, entrepreneurial: 30, caring: 99 }
  },
  {
    id: '47',
    name: 'Data Analyst',
    cluster: 'Technology & AI',
    description: 'Turn raw data into business insights. Create dashboards, find patterns, and help companies make better decisions.',
    skills: ['SQL', 'Excel', 'Python/R', 'Tableau/Power BI', 'Statistics', 'Communication'],
    salary_range: { min: 400000, max: 1800000, currency: 'INR' },
    ai_risk_score: 50,
    growth_trend: 'stable',
    education_path: 'Any degree with quantitative skills. BTech, BSc Stats, BBA + analytics certifications.',
    day_in_life: 'Query databases, clean data, build dashboards, present insights to stakeholders, identify trends.',
    icon: '📉',
    identity_match: { creative: 20, analytical: 90, social: 40, practical: 60, entrepreneurial: 30, caring: 10 }
  },
  {
    id: '48',
    name: 'Nutritionist / Dietitian',
    cluster: 'Healthcare & Wellness',
    description: 'Help people eat better and manage health conditions through food. Combine science and wellness.',
    skills: ['Nutrition Science', 'Meal Planning', 'Client Counseling', 'Biochemistry', 'Communication', 'Empathy'],
    salary_range: { min: 300000, max: 1200000, currency: 'INR' },
    ai_risk_score: 15,
    growth_trend: 'rising',
    education_path: 'BSc Nutrition/Dietetics → MSc. Registration with IDA. Clinical internship required.',
    day_in_life: 'Assess client health, create meal plans, counsel on lifestyle changes, track progress, stay updated on research.',
    icon: '🥗',
    identity_match: { creative: 30, analytical: 50, social: 70, practical: 60, entrepreneurial: 40, caring: 85 }
  },
  {
    id: '49',
    name: 'Foreign Language Specialist / Translator',
    cluster: 'Education',
    description: 'Bridge language barriers — translate, interpret, teach, or work in international relations.',
    skills: ['Language Proficiency', 'Cultural Awareness', 'Writing', 'Communication', 'Attention to Detail', 'Diplomacy'],
    salary_range: { min: 300000, max: 1500000, currency: 'INR' },
    ai_risk_score: 55,
    growth_trend: 'stable',
    education_path: 'BA in foreign language (JNU, BHU, DU). Certifications in specific languages. Immersion helps.',
    day_in_life: 'Translate documents, interpret at meetings, teach language classes, localize content, assist in diplomatic settings.',
    icon: '🌐',
    identity_match: { creative: 40, analytical: 50, social: 80, practical: 40, entrepreneurial: 30, caring: 40 }
  },
  {
    id: '50',
    name: 'Space Scientist / ISRO Engineer',
    cluster: 'Science & Research',
    description: 'Design satellites, rockets, and space missions. India\'s space program is one of the world\'s most ambitious.',
    skills: ['Physics', 'Mathematics', 'Programming', 'Aerospace Engineering', 'Research', 'Problem Solving'],
    salary_range: { min: 600000, max: 2000000, currency: 'INR' },
    ai_risk_score: 10,
    growth_trend: 'rising',
    education_path: 'BTech/MSc in Aerospace/Physics/Electronics → ISRO entrance exam. PhD for research scientists.',
    day_in_life: 'Design spacecraft systems, run simulations, analyze mission data, collaborate on research, test equipment.',
    icon: '🚀',
    identity_match: { creative: 40, analytical: 95, social: 20, practical: 70, entrepreneurial: 30, caring: 20 }
  }
];

export const careerClusters = [
  'Technology & AI',
  'Design & Creative',
  'Healthcare & Wellness',
  'Business & Strategy',
  'Science & Research',
  'Media & Entertainment',
  'Finance & Commerce',
  'Government & Public Policy',
  'Law & Governance',
  'Education',
  'Social Impact',
  'Engineering',
  'Sports & Fitness',
  'Arts & Performance',
  'Hospitality & Food',
  'Aviation & Transport',
];
