export interface College {
  id: string;
  name: string;
  type: 'IIT' | 'NIT' | 'IIIT' | 'Central University' | 'State University' | 'Private' | 'Deemed' | 'Autonomous';
  city: string;
  state: string;
  streams: string[];
  ranking?: number;
  entranceExams: string[];
  avgFees: { min: number; max: number };
  avgPlacement: { min: number; max: number };
  website: string;
  highlights: string[];
}

export const colleges: College[] = [
  // === IITs (23) ===
  {
    id: 'iit-bombay',
    name: 'IIT Bombay',
    type: 'IIT',
    city: 'Mumbai',
    state: 'Maharashtra',
    streams: ['Engineering', 'Science', 'Design', 'Management'],
    ranking: 3,
    entranceExams: ['JEE Advanced', 'GATE', 'CAT', 'CEED'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1500000, max: 3000000 },
    website: 'https://www.iitb.ac.in',
    highlights: ['Top 3 in India', 'Strong startup culture', 'IDC School of Design', 'Excellent research output'],
  },
  {
    id: 'iit-delhi',
    name: 'IIT Delhi',
    type: 'IIT',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Engineering', 'Science', 'Design', 'Management'],
    ranking: 2,
    entranceExams: ['JEE Advanced', 'GATE', 'CAT'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1600000, max: 3200000 },
    website: 'https://home.iitd.ac.in',
    highlights: ['NIRF #2', 'Strong industry connections', 'Located in national capital', 'Top research institute'],
  },
  {
    id: 'iit-madras',
    name: 'IIT Madras',
    type: 'IIT',
    city: 'Chennai',
    state: 'Tamil Nadu',
    streams: ['Engineering', 'Science', 'Management'],
    ranking: 1,
    entranceExams: ['JEE Advanced', 'GATE', 'CAT'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1400000, max: 2800000 },
    website: 'https://www.iitm.ac.in',
    highlights: ['NIRF #1 consistently', 'IIT Madras Research Park', 'BS online degree program', 'Strong in AI/ML research'],
  },
  {
    id: 'iit-kanpur',
    name: 'IIT Kanpur',
    type: 'IIT',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    streams: ['Engineering', 'Science', 'Management', 'Design'],
    ranking: 4,
    entranceExams: ['JEE Advanced', 'GATE', 'CAT'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1300000, max: 2600000 },
    website: 'https://www.iitk.ac.in',
    highlights: ['Strong CS and Aerospace programs', 'Pioneer in computer education in India', 'SIDBI Innovation Center'],
  },
  {
    id: 'iit-kharagpur',
    name: 'IIT Kharagpur',
    type: 'IIT',
    city: 'Kharagpur',
    state: 'West Bengal',
    streams: ['Engineering', 'Science', 'Law', 'Management', 'Architecture'],
    ranking: 5,
    entranceExams: ['JEE Advanced', 'GATE', 'CAT'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1200000, max: 2500000 },
    website: 'https://www.iitkgp.ac.in',
    highlights: ['Oldest IIT (1951)', 'Largest IIT campus', 'Rajiv Gandhi School of IP Law', 'Vinod Gupta School of Management'],
  },
  {
    id: 'iit-roorkee',
    name: 'IIT Roorkee',
    type: 'IIT',
    city: 'Roorkee',
    state: 'Uttarakhand',
    streams: ['Engineering', 'Science', 'Architecture', 'Management'],
    ranking: 6,
    entranceExams: ['JEE Advanced', 'GATE', 'CAT'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1100000, max: 2200000 },
    website: 'https://www.iitr.ac.in',
    highlights: ['Founded in 1847 as Thomason College', 'Strong civil and architecture programs', 'Heritage campus'],
  },
  {
    id: 'iit-guwahati',
    name: 'IIT Guwahati',
    type: 'IIT',
    city: 'Guwahati',
    state: 'Assam',
    streams: ['Engineering', 'Science', 'Design'],
    ranking: 7,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1000000, max: 2000000 },
    website: 'https://www.iitg.ac.in',
    highlights: ['Beautiful Brahmaputra campus', 'Strong Design department', 'Growing research output', 'Northeast hub for tech'],
  },
  {
    id: 'iit-hyderabad',
    name: 'IIT Hyderabad',
    type: 'IIT',
    city: 'Hyderabad',
    state: 'Telangana',
    streams: ['Engineering', 'Science', 'Design', 'Liberal Arts'],
    ranking: 8,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1000000, max: 2200000 },
    website: 'https://www.iith.ac.in',
    highlights: ['Fractal academics structure', 'Strong AI/ML focus', 'Japanese collaboration', 'Fast-growing research'],
  },
  {
    id: 'iit-indore',
    name: 'IIT Indore',
    type: 'IIT',
    city: 'Indore',
    state: 'Madhya Pradesh',
    streams: ['Engineering', 'Science'],
    ranking: 10,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 900000, max: 1800000 },
    website: 'https://www.iiti.ac.in',
    highlights: ['Rapidly growing', 'Strong research publications', 'Modern campus'],
  },
  {
    id: 'iit-bhu',
    name: 'IIT (BHU) Varanasi',
    type: 'IIT',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    streams: ['Engineering', 'Science', 'Pharmacy', 'Mining'],
    ranking: 11,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 1000000, max: 2000000 },
    website: 'https://www.iitbhu.ac.in',
    highlights: ['Part of BHU heritage', 'Strong metallurgy and mining', 'Cultural campus in Varanasi'],
  },
  {
    id: 'iit-ropar',
    name: 'IIT Ropar',
    type: 'IIT',
    city: 'Rupnagar',
    state: 'Punjab',
    streams: ['Engineering', 'Science'],
    ranking: 18,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 800000, max: 1600000 },
    website: 'https://www.iitrpr.ac.in',
    highlights: ['Growing rapidly', 'Biomedical engineering focus', 'New campus development'],
  },
  {
    id: 'iit-patna',
    name: 'IIT Patna',
    type: 'IIT',
    city: 'Patna',
    state: 'Bihar',
    streams: ['Engineering', 'Science'],
    ranking: 22,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 800000, max: 1500000 },
    website: 'https://www.iitp.ac.in',
    highlights: ['New IIT with modern infrastructure', 'Strong CS department', 'Bihta campus'],
  },
  {
    id: 'iit-gandhinagar',
    name: 'IIT Gandhinagar',
    type: 'IIT',
    city: 'Gandhinagar',
    state: 'Gujarat',
    streams: ['Engineering', 'Science', 'Liberal Arts'],
    ranking: 15,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 900000, max: 1800000 },
    website: 'https://www.iitgn.ac.in',
    highlights: ['Liberal arts foundation', 'Explorer fellowships', 'Strong cognitive science', 'Innovation in pedagogy'],
  },
  {
    id: 'iit-jodhpur',
    name: 'IIT Jodhpur',
    type: 'IIT',
    city: 'Jodhpur',
    state: 'Rajasthan',
    streams: ['Engineering', 'Science'],
    ranking: 25,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 800000, max: 1500000 },
    website: 'https://www.iitj.ac.in',
    highlights: ['Desert-based research', 'Solar energy focus', 'Digital humanities'],
  },
  {
    id: 'iit-mandi',
    name: 'IIT Mandi',
    type: 'IIT',
    city: 'Mandi',
    state: 'Himachal Pradesh',
    streams: ['Engineering', 'Science'],
    ranking: 20,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 800000, max: 1500000 },
    website: 'https://www.iitmandi.ac.in',
    highlights: ['Himalayan campus', 'Project-based learning', 'Catalyst incubator'],
  },
  {
    id: 'iit-bhubaneswar',
    name: 'IIT Bhubaneswar',
    type: 'IIT',
    city: 'Bhubaneswar',
    state: 'Odisha',
    streams: ['Engineering', 'Science'],
    ranking: 23,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 800000, max: 1500000 },
    website: 'https://www.iitbbs.ac.in',
    highlights: ['Argul campus', 'School of Earth Sciences', 'Climate research'],
  },
  {
    id: 'iit-tirupati',
    name: 'IIT Tirupati',
    type: 'IIT',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    streams: ['Engineering', 'Science'],
    ranking: 35,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 700000, max: 1400000 },
    website: 'https://www.iittp.ac.in',
    highlights: ['Mentored by IIT Madras', 'Growing campus', 'Yerpedu location'],
  },
  {
    id: 'iit-dhanbad',
    name: 'IIT (ISM) Dhanbad',
    type: 'IIT',
    city: 'Dhanbad',
    state: 'Jharkhand',
    streams: ['Engineering', 'Science', 'Mining'],
    ranking: 12,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 900000, max: 1800000 },
    website: 'https://www.iitism.ac.in',
    highlights: ['Former Indian School of Mines', 'Best mining and petroleum programs', 'Heritage institution'],
  },
  {
    id: 'iit-bhilai',
    name: 'IIT Bhilai',
    type: 'IIT',
    city: 'Bhilai',
    state: 'Chhattisgarh',
    streams: ['Engineering', 'Science'],
    ranking: 45,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 700000, max: 1300000 },
    website: 'https://www.iitbhilai.ac.in',
    highlights: ['Liberal education approach', 'Data science focus', 'New generation IIT'],
  },
  {
    id: 'iit-goa',
    name: 'IIT Goa',
    type: 'IIT',
    city: 'Ponda',
    state: 'Goa',
    streams: ['Engineering', 'Science'],
    ranking: 48,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 700000, max: 1200000 },
    website: 'https://www.iitgoa.ac.in',
    highlights: ['Mentored by IIT Bombay', 'Mathematics focus', 'Coastal campus'],
  },
  {
    id: 'iit-jammu',
    name: 'IIT Jammu',
    type: 'IIT',
    city: 'Jammu',
    state: 'Jammu & Kashmir',
    streams: ['Engineering', 'Science'],
    ranking: 50,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 600000, max: 1200000 },
    website: 'https://www.iitjammu.ac.in',
    highlights: ['Scenic Himalayan campus', 'Smart manufacturing focus', 'Growing rapidly'],
  },
  {
    id: 'iit-dharwad',
    name: 'IIT Dharwad',
    type: 'IIT',
    city: 'Dharwad',
    state: 'Karnataka',
    streams: ['Engineering', 'Science'],
    ranking: 55,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 600000, max: 1200000 },
    website: 'https://www.iitdh.ac.in',
    highlights: ['Mentored by IIT Bombay', 'Karnataka tech ecosystem', 'New generation IIT'],
  },
  {
    id: 'iit-palakkad',
    name: 'IIT Palakkad',
    type: 'IIT',
    city: 'Palakkad',
    state: 'Kerala',
    streams: ['Engineering', 'Science'],
    ranking: 52,
    entranceExams: ['JEE Advanced', 'GATE'],
    avgFees: { min: 200000, max: 250000 },
    avgPlacement: { min: 600000, max: 1200000 },
    website: 'https://www.iitpkd.ac.in',
    highlights: ['Mentored by IIT Madras', 'Data science programs', 'Kerala tech hub'],
  },

  // === NITs (10) ===
  {
    id: 'nit-trichy',
    name: 'NIT Tiruchirappalli',
    type: 'NIT',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    streams: ['Engineering', 'Science', 'Architecture', 'Management'],
    ranking: 9,
    entranceExams: ['JEE Main', 'GATE', 'CAT'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 900000, max: 1800000 },
    website: 'https://www.nitt.edu',
    highlights: ['Top NIT consistently', 'Strong alumni network', 'Pragyan tech fest', 'Great ROI'],
  },
  {
    id: 'nit-surathkal',
    name: 'NIT Karnataka (Surathkal)',
    type: 'NIT',
    city: 'Mangalore',
    state: 'Karnataka',
    streams: ['Engineering', 'Science'],
    ranking: 13,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 800000, max: 1700000 },
    website: 'https://www.nitk.ac.in',
    highlights: ['Beach campus', 'Strong IT placements', 'Engineer tech fest', 'Top 3 NIT'],
  },
  {
    id: 'nit-warangal',
    name: 'NIT Warangal',
    type: 'NIT',
    city: 'Warangal',
    state: 'Telangana',
    streams: ['Engineering', 'Science', 'Management'],
    ranking: 14,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 800000, max: 1600000 },
    website: 'https://www.nitw.ac.in',
    highlights: ['One of the first RECs', 'Technozion fest', 'Strong ECE department', 'Great placements'],
  },
  {
    id: 'nit-rourkela',
    name: 'NIT Rourkela',
    type: 'NIT',
    city: 'Rourkela',
    state: 'Odisha',
    streams: ['Engineering', 'Science', 'Management'],
    ranking: 16,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 700000, max: 1500000 },
    website: 'https://www.nitrkl.ac.in',
    highlights: ['Strong metallurgy program', 'NIT Rourkela Innovation Center', 'Good campus life'],
  },
  {
    id: 'nit-calicut',
    name: 'NIT Calicut',
    type: 'NIT',
    city: 'Kozhikode',
    state: 'Kerala',
    streams: ['Engineering', 'Science', 'Architecture'],
    ranking: 17,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 700000, max: 1400000 },
    website: 'https://www.nitc.ac.in',
    highlights: ['Scenic campus in Kerala', 'Strong CS and ECE', 'Ragam cultural fest'],
  },
  {
    id: 'nit-nagpur',
    name: 'VNIT Nagpur',
    type: 'NIT',
    city: 'Nagpur',
    state: 'Maharashtra',
    streams: ['Engineering', 'Science'],
    ranking: 19,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 700000, max: 1400000 },
    website: 'https://vnit.ac.in',
    highlights: ['Central India hub', 'Axis tech fest', 'Strong mining engineering'],
  },
  {
    id: 'nit-allahabad',
    name: 'MNNIT Allahabad',
    type: 'NIT',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    streams: ['Engineering', 'Science', 'Management'],
    ranking: 21,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 600000, max: 1300000 },
    website: 'https://www.mnnit.ac.in',
    highlights: ['Historic city campus', 'Strong biotech department', 'Avishkar fest'],
  },
  {
    id: 'nit-jaipur',
    name: 'MNIT Jaipur',
    type: 'NIT',
    city: 'Jaipur',
    state: 'Rajasthan',
    streams: ['Engineering', 'Science', 'Architecture'],
    ranking: 24,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 600000, max: 1200000 },
    website: 'https://www.mnit.ac.in',
    highlights: ['Pink City campus', 'Strong architecture program', 'BLISS fest'],
  },
  {
    id: 'nit-kurukshetra',
    name: 'NIT Kurukshetra',
    type: 'NIT',
    city: 'Kurukshetra',
    state: 'Haryana',
    streams: ['Engineering', 'Science', 'Management'],
    ranking: 26,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 600000, max: 1200000 },
    website: 'https://www.nitkkr.ac.in',
    highlights: ['One of the oldest NITs', 'Strong placement record', 'Techspardha fest'],
  },
  {
    id: 'nit-durgapur',
    name: 'NIT Durgapur',
    type: 'NIT',
    city: 'Durgapur',
    state: 'West Bengal',
    streams: ['Engineering', 'Science', 'Management'],
    ranking: 28,
    entranceExams: ['JEE Main', 'GATE'],
    avgFees: { min: 125000, max: 175000 },
    avgPlacement: { min: 500000, max: 1100000 },
    website: 'https://nitdgp.ac.in',
    highlights: ['Bengal engineering hub', 'Aarohan tech fest', 'Strong ECE and CS'],
  },

  // === IIITs (5) ===
  {
    id: 'iiit-hyderabad',
    name: 'IIIT Hyderabad',
    type: 'IIIT',
    city: 'Hyderabad',
    state: 'Telangana',
    streams: ['Engineering', 'Science'],
    ranking: 30,
    entranceExams: ['JEE Main', 'IIIT-H entrance'],
    avgFees: { min: 300000, max: 400000 },
    avgPlacement: { min: 1200000, max: 2800000 },
    website: 'https://www.iiit.ac.in',
    highlights: ['Top CS college in India', 'Research-driven', 'KCIS lab', 'Strong ML/AI programs'],
  },
  {
    id: 'iiit-bangalore',
    name: 'IIIT Bangalore',
    type: 'IIIT',
    city: 'Bangalore',
    state: 'Karnataka',
    streams: ['Engineering'],
    ranking: 40,
    entranceExams: ['JEE Main', 'IIITB entrance'],
    avgFees: { min: 350000, max: 450000 },
    avgPlacement: { min: 1100000, max: 2500000 },
    website: 'https://www.iiitb.ac.in',
    highlights: ['Silicon Valley of India location', 'Integrated MTech', 'Strong industry connect'],
  },
  {
    id: 'iiit-allahabad',
    name: 'IIIT Allahabad',
    type: 'IIIT',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    streams: ['Engineering', 'Management'],
    ranking: 42,
    entranceExams: ['JEE Main'],
    avgFees: { min: 150000, max: 200000 },
    avgPlacement: { min: 800000, max: 1800000 },
    website: 'https://www.iiita.ac.in',
    highlights: ['IT and management programs', 'Effervescence fest', 'Good placements for fees'],
  },
  {
    id: 'iiit-delhi',
    name: 'IIIT Delhi',
    type: 'IIIT',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Engineering'],
    ranking: 36,
    entranceExams: ['JEE Main', 'JAC Delhi'],
    avgFees: { min: 300000, max: 400000 },
    avgPlacement: { min: 1100000, max: 2400000 },
    website: 'https://www.iiitd.ac.in',
    highlights: ['Strong CS curriculum', 'Research focus', 'Startup ecosystem', 'AI/ML specializations'],
  },
  {
    id: 'iiit-gwalior',
    name: 'ABV-IIITM Gwalior',
    type: 'IIIT',
    city: 'Gwalior',
    state: 'Madhya Pradesh',
    streams: ['Engineering', 'Management'],
    ranking: 60,
    entranceExams: ['JEE Main'],
    avgFees: { min: 150000, max: 200000 },
    avgPlacement: { min: 700000, max: 1400000 },
    website: 'https://www.iiitm.ac.in',
    highlights: ['IT and Management dual focus', 'IPR and cyber law programs', 'Good value for money'],
  },

  // === Medical ===
  {
    id: 'aiims-delhi',
    name: 'AIIMS New Delhi',
    type: 'Autonomous',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Medical', 'Nursing', 'Paramedical'],
    ranking: 1,
    entranceExams: ['NEET UG', 'NEET PG', 'INI-CET'],
    avgFees: { min: 5000, max: 10000 },
    avgPlacement: { min: 1200000, max: 3000000 },
    website: 'https://www.aiims.edu',
    highlights: ['Best medical college in India', 'Minimal fees', 'World-class faculty', 'Cutting-edge research'],
  },
  {
    id: 'cmc-vellore',
    name: 'Christian Medical College, Vellore',
    type: 'Deemed',
    city: 'Vellore',
    state: 'Tamil Nadu',
    streams: ['Medical', 'Nursing', 'Allied Health'],
    ranking: 3,
    entranceExams: ['NEET UG'],
    avgFees: { min: 50000, max: 100000 },
    avgPlacement: { min: 800000, max: 1800000 },
    website: 'https://www.cmch-vellore.edu',
    highlights: ['Top 3 medical college', 'Mission-driven', 'Excellent clinical training', 'Low fees'],
  },
  {
    id: 'afmc-pune',
    name: 'Armed Forces Medical College, Pune',
    type: 'Autonomous',
    city: 'Pune',
    state: 'Maharashtra',
    streams: ['Medical'],
    ranking: 5,
    entranceExams: ['NEET UG'],
    avgFees: { min: 30000, max: 60000 },
    avgPlacement: { min: 1000000, max: 2000000 },
    website: 'https://afmc.nic.in',
    highlights: ['Military medical training', 'Highly disciplined environment', 'Service commitment', 'Low fees'],
  },
  {
    id: 'mamc-delhi',
    name: 'Maulana Azad Medical College',
    type: 'State University',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Medical'],
    ranking: 7,
    entranceExams: ['NEET UG'],
    avgFees: { min: 20000, max: 50000 },
    avgPlacement: { min: 800000, max: 1500000 },
    website: 'https://www.mamc.ac.in',
    highlights: ['Top Delhi medical college', 'Lok Nayak Hospital affiliation', 'Excellent PG programs'],
  },
  {
    id: 'jipmer-puducherry',
    name: 'JIPMER Puducherry',
    type: 'Autonomous',
    city: 'Puducherry',
    state: 'Puducherry',
    streams: ['Medical', 'Nursing'],
    ranking: 4,
    entranceExams: ['NEET UG', 'INI-CET'],
    avgFees: { min: 10000, max: 25000 },
    avgPlacement: { min: 900000, max: 1800000 },
    website: 'https://www.jipmer.edu.in',
    highlights: ['Institute of National Importance', 'Very low fees', 'Strong clinical research'],
  },

  // === Design ===
  {
    id: 'nid-ahmedabad',
    name: 'National Institute of Design, Ahmedabad',
    type: 'Autonomous',
    city: 'Ahmedabad',
    state: 'Gujarat',
    streams: ['Design'],
    ranking: 1,
    entranceExams: ['NID DAT'],
    avgFees: { min: 300000, max: 400000 },
    avgPlacement: { min: 800000, max: 2000000 },
    website: 'https://www.nid.edu',
    highlights: ['Premier design institute', 'Product, textile, animation design', 'Industry collaborations', 'Iconic alumni'],
  },
  {
    id: 'nift-delhi',
    name: 'NIFT Delhi',
    type: 'Autonomous',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Design', 'Fashion', 'Management'],
    ranking: 1,
    entranceExams: ['NIFT Entrance'],
    avgFees: { min: 200000, max: 350000 },
    avgPlacement: { min: 500000, max: 1500000 },
    website: 'https://www.nift.ac.in',
    highlights: ['Top fashion institute', 'Fashion design and technology', 'Global collaborations'],
  },

  // === Law (NLUs) ===
  {
    id: 'nlsiu-bangalore',
    name: 'NLSIU Bangalore',
    type: 'Autonomous',
    city: 'Bangalore',
    state: 'Karnataka',
    streams: ['Law'],
    ranking: 1,
    entranceExams: ['CLAT', 'NLSIU entrance'],
    avgFees: { min: 200000, max: 300000 },
    avgPlacement: { min: 1200000, max: 3000000 },
    website: 'https://www.nls.ac.in',
    highlights: ['Best law school in India', 'Pioneer of 5-year integrated law', 'Top-tier placements'],
  },
  {
    id: 'nalsar-hyderabad',
    name: 'NALSAR Hyderabad',
    type: 'Autonomous',
    city: 'Hyderabad',
    state: 'Telangana',
    streams: ['Law'],
    ranking: 2,
    entranceExams: ['CLAT'],
    avgFees: { min: 200000, max: 280000 },
    avgPlacement: { min: 1000000, max: 2500000 },
    website: 'https://www.nalsar.ac.in',
    highlights: ['Top 3 NLU', 'IPR specialization', 'Strong moot court culture'],
  },
  {
    id: 'nlu-delhi',
    name: 'NLU Delhi',
    type: 'Autonomous',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Law'],
    ranking: 3,
    entranceExams: ['AILET'],
    avgFees: { min: 200000, max: 300000 },
    avgPlacement: { min: 1000000, max: 2500000 },
    website: 'https://nludelhi.ac.in',
    highlights: ['Own entrance exam (AILET)', 'Capital city advantage', 'Supreme Court proximity'],
  },
  {
    id: 'wbnujs-kolkata',
    name: 'NUJS Kolkata',
    type: 'Autonomous',
    city: 'Kolkata',
    state: 'West Bengal',
    streams: ['Law'],
    ranking: 4,
    entranceExams: ['CLAT'],
    avgFees: { min: 180000, max: 250000 },
    avgPlacement: { min: 900000, max: 2000000 },
    website: 'https://www.nujs.edu',
    highlights: ['Top 5 NLU', 'Corporate law focus', 'Strong alumni in top law firms'],
  },

  // === Management (IIMs) ===
  {
    id: 'iim-ahmedabad',
    name: 'IIM Ahmedabad',
    type: 'Autonomous',
    city: 'Ahmedabad',
    state: 'Gujarat',
    streams: ['Management'],
    ranking: 1,
    entranceExams: ['CAT', 'GMAT'],
    avgFees: { min: 2300000, max: 2500000 },
    avgPlacement: { min: 2500000, max: 4000000 },
    website: 'https://www.iima.ac.in',
    highlights: ['Top B-school in India', 'Case study method', 'Louis Kahn architecture', 'Iconic alumni'],
  },
  {
    id: 'iim-bangalore',
    name: 'IIM Bangalore',
    type: 'Autonomous',
    city: 'Bangalore',
    state: 'Karnataka',
    streams: ['Management'],
    ranking: 2,
    entranceExams: ['CAT', 'GMAT'],
    avgFees: { min: 2300000, max: 2500000 },
    avgPlacement: { min: 2400000, max: 3800000 },
    website: 'https://www.iimb.ac.in',
    highlights: ['Top 2 B-school', 'Silicon Valley of India', 'NSRCEL startup hub', 'Strong consulting placements'],
  },
  {
    id: 'iim-calcutta',
    name: 'IIM Calcutta',
    type: 'Autonomous',
    city: 'Kolkata',
    state: 'West Bengal',
    streams: ['Management'],
    ranking: 3,
    entranceExams: ['CAT', 'GMAT'],
    avgFees: { min: 2200000, max: 2400000 },
    avgPlacement: { min: 2300000, max: 3500000 },
    website: 'https://www.iimcal.ac.in',
    highlights: ['Oldest IIM (1961)', 'Finance specialization', 'Joka campus', 'Strong quant programs'],
  },
  {
    id: 'iim-lucknow',
    name: 'IIM Lucknow',
    type: 'Autonomous',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    streams: ['Management'],
    ranking: 4,
    entranceExams: ['CAT'],
    avgFees: { min: 1900000, max: 2100000 },
    avgPlacement: { min: 2000000, max: 3200000 },
    website: 'https://www.iiml.ac.in',
    highlights: ['Top 5 IIM', 'Strong HR and marketing programs', 'Noida campus for working professionals'],
  },
  {
    id: 'iim-kozhikode',
    name: 'IIM Kozhikode',
    type: 'Autonomous',
    city: 'Kozhikode',
    state: 'Kerala',
    streams: ['Management'],
    ranking: 5,
    entranceExams: ['CAT'],
    avgFees: { min: 1800000, max: 2000000 },
    avgPlacement: { min: 1800000, max: 3000000 },
    website: 'https://www.iimk.ac.in',
    highlights: ['Hilltop campus', 'Strong strategy programs', 'LIVE business projects', 'International tie-ups'],
  },
  {
    id: 'iim-indore',
    name: 'IIM Indore',
    type: 'Autonomous',
    city: 'Indore',
    state: 'Madhya Pradesh',
    streams: ['Management'],
    ranking: 6,
    entranceExams: ['CAT'],
    avgFees: { min: 1800000, max: 2000000 },
    avgPlacement: { min: 1700000, max: 2800000 },
    website: 'https://www.iimidr.ac.in',
    highlights: ['IPM program (5-year integrated)', 'Strong marketing programs', 'Top 7 IIM'],
  },

  // === Central Universities ===
  {
    id: 'du',
    name: 'University of Delhi',
    type: 'Central University',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Arts', 'Science', 'Commerce', 'Law', 'Medical'],
    ranking: 11,
    entranceExams: ['CUET'],
    avgFees: { min: 15000, max: 50000 },
    avgPlacement: { min: 400000, max: 1200000 },
    website: 'https://www.du.ac.in',
    highlights: ['Premier central university', '90+ affiliated colleges', 'North Campus iconic culture', 'Wide range of programs'],
  },
  {
    id: 'jnu',
    name: 'Jawaharlal Nehru University',
    type: 'Central University',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Arts', 'Science', 'Social Sciences', 'Languages'],
    ranking: 2,
    entranceExams: ['CUET', 'JNU entrance'],
    avgFees: { min: 500, max: 5000 },
    avgPlacement: { min: 400000, max: 1000000 },
    website: 'https://www.jnu.ac.in',
    highlights: ['Top for social sciences', 'Almost free education', 'Research-intensive', 'Vibrant campus life'],
  },
  {
    id: 'bhu',
    name: 'Banaras Hindu University',
    type: 'Central University',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    streams: ['Arts', 'Science', 'Commerce', 'Engineering', 'Medical', 'Law', 'Agriculture'],
    ranking: 6,
    entranceExams: ['CUET', 'JEE Advanced (IIT-BHU)'],
    avgFees: { min: 10000, max: 50000 },
    avgPlacement: { min: 400000, max: 1200000 },
    website: 'https://www.bhu.ac.in',
    highlights: ['Largest residential university in Asia', 'Founded by Madan Mohan Malaviya', 'IIT-BHU within campus', 'Heritage institution'],
  },
  {
    id: 'jamia',
    name: 'Jamia Millia Islamia',
    type: 'Central University',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Arts', 'Science', 'Engineering', 'Architecture', 'Law', 'Education'],
    ranking: 15,
    entranceExams: ['CUET', 'JMI entrance'],
    avgFees: { min: 10000, max: 40000 },
    avgPlacement: { min: 400000, max: 900000 },
    website: 'https://www.jmi.ac.in',
    highlights: ['Central university in Delhi', 'AJK Mass Communication Centre', 'Architecture and Fine Arts programs'],
  },
  {
    id: 'amu',
    name: 'Aligarh Muslim University',
    type: 'Central University',
    city: 'Aligarh',
    state: 'Uttar Pradesh',
    streams: ['Arts', 'Science', 'Commerce', 'Engineering', 'Medical', 'Law'],
    ranking: 20,
    entranceExams: ['CUET', 'AMU entrance'],
    avgFees: { min: 10000, max: 40000 },
    avgPlacement: { min: 400000, max: 900000 },
    website: 'https://www.amu.ac.in',
    highlights: ['Historic university', 'Wide range of programs', 'Strong medical and engineering faculties'],
  },
  {
    id: 'uoh',
    name: 'University of Hyderabad',
    type: 'Central University',
    city: 'Hyderabad',
    state: 'Telangana',
    streams: ['Arts', 'Science', 'Social Sciences'],
    ranking: 8,
    entranceExams: ['CUET'],
    avgFees: { min: 5000, max: 20000 },
    avgPlacement: { min: 400000, max: 800000 },
    website: 'https://www.uohyd.ac.in',
    highlights: ['Strong sciences and humanities', 'Research focus', 'Affordable education', 'Green campus'],
  },

  // === DU Colleges ===
  {
    id: 'srcc',
    name: 'Shri Ram College of Commerce (SRCC)',
    type: 'Autonomous',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Commerce', 'Economics'],
    ranking: 1,
    entranceExams: ['CUET'],
    avgFees: { min: 20000, max: 40000 },
    avgPlacement: { min: 800000, max: 2000000 },
    website: 'https://www.srcc.edu',
    highlights: ['Best commerce college in India', 'Iconic North Campus', 'Business Conclave', 'Top-tier placements'],
  },
  {
    id: 'stephens',
    name: "St. Stephen's College",
    type: 'Autonomous',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Arts', 'Science', 'Commerce'],
    ranking: 2,
    entranceExams: ['CUET', 'College interview'],
    avgFees: { min: 30000, max: 60000 },
    avgPlacement: { min: 500000, max: 1200000 },
    website: 'https://www.ststephens.edu',
    highlights: ['Most prestigious DU college', 'Liberal arts focus', 'Illustrious alumni', 'Historic campus'],
  },
  {
    id: 'hindu-college',
    name: 'Hindu College',
    type: 'Autonomous',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Arts', 'Science', 'Commerce'],
    ranking: 3,
    entranceExams: ['CUET'],
    avgFees: { min: 15000, max: 35000 },
    avgPlacement: { min: 500000, max: 1100000 },
    website: 'https://www.hinducollege.ac.in',
    highlights: ['Top DU college', 'Strong sciences', 'Mecca for economics', 'North Campus culture'],
  },
  {
    id: 'lsr',
    name: 'Lady Shri Ram College for Women',
    type: 'Autonomous',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Arts', 'Science', 'Commerce'],
    ranking: 4,
    entranceExams: ['CUET'],
    avgFees: { min: 15000, max: 35000 },
    avgPlacement: { min: 500000, max: 1000000 },
    website: 'https://www.lsr.edu.in',
    highlights: ['Best women\'s college', 'Strong humanities', 'Empowering environment', 'Illustrious alumni'],
  },

  // === Private Universities ===
  {
    id: 'bits-pilani',
    name: 'BITS Pilani',
    type: 'Private',
    city: 'Pilani',
    state: 'Rajasthan',
    streams: ['Engineering', 'Science', 'Pharmacy', 'Management'],
    ranking: 27,
    entranceExams: ['BITSAT'],
    avgFees: { min: 500000, max: 600000 },
    avgPlacement: { min: 1000000, max: 2500000 },
    website: 'https://www.bits-pilani.ac.in',
    highlights: ['Practice School internship model', 'Flexible dual-degree', 'Campuses in Goa, Hyderabad, Dubai', 'Strong alumni network'],
  },
  {
    id: 'vit-vellore',
    name: 'VIT Vellore',
    type: 'Private',
    city: 'Vellore',
    state: 'Tamil Nadu',
    streams: ['Engineering', 'Science', 'Management'],
    ranking: 15,
    entranceExams: ['VITEEE'],
    avgFees: { min: 200000, max: 350000 },
    avgPlacement: { min: 600000, max: 1500000 },
    website: 'https://www.vit.ac.in',
    highlights: ['Largest private university for engineering', 'NAAC A++ grade', 'Strong placement record', 'Multiple campuses'],
  },
  {
    id: 'srm-chennai',
    name: 'SRM Institute of Science and Technology',
    type: 'Private',
    city: 'Chennai',
    state: 'Tamil Nadu',
    streams: ['Engineering', 'Science', 'Medical', 'Management'],
    ranking: 30,
    entranceExams: ['SRMJEEE'],
    avgFees: { min: 250000, max: 400000 },
    avgPlacement: { min: 500000, max: 1200000 },
    website: 'https://www.srmist.edu.in',
    highlights: ['Large campus', 'International collaborations', 'Multiple campuses across India'],
  },
  {
    id: 'manipal',
    name: 'Manipal Academy of Higher Education',
    type: 'Deemed',
    city: 'Manipal',
    state: 'Karnataka',
    streams: ['Engineering', 'Medical', 'Management', 'Design', 'Commerce', 'Arts'],
    ranking: 8,
    entranceExams: ['MET'],
    avgFees: { min: 300000, max: 500000 },
    avgPlacement: { min: 600000, max: 1500000 },
    website: 'https://www.manipal.edu',
    highlights: ['University town concept', 'Excellent medical college', 'Strong industry partnerships', 'Beautiful campus'],
  },
  {
    id: 'ashoka',
    name: 'Ashoka University',
    type: 'Private',
    city: 'Sonepat',
    state: 'Haryana',
    streams: ['Arts', 'Science', 'Economics', 'Social Sciences'],
    ranking: 38,
    entranceExams: ['Ashoka entrance'],
    avgFees: { min: 900000, max: 1100000 },
    avgPlacement: { min: 600000, max: 1500000 },
    website: 'https://www.ashoka.edu.in',
    highlights: ['Liberal arts pioneer in India', 'World-class faculty', 'Need-blind admissions', 'Research focus'],
  },
  {
    id: 'jindal-global',
    name: 'O.P. Jindal Global University',
    type: 'Private',
    city: 'Sonepat',
    state: 'Haryana',
    streams: ['Law', 'Management', 'Arts', 'Public Policy'],
    ranking: 36,
    entranceExams: ['LSAT India', 'JGLS entrance'],
    avgFees: { min: 600000, max: 1000000 },
    avgPlacement: { min: 700000, max: 1800000 },
    website: 'https://www.jgu.edu.in',
    highlights: ['Top private law school', 'Global curriculum', 'International faculty', 'Young and dynamic'],
  },
  {
    id: 'christ-bangalore',
    name: 'Christ University',
    type: 'Deemed',
    city: 'Bangalore',
    state: 'Karnataka',
    streams: ['Arts', 'Science', 'Commerce', 'Management', 'Law', 'Engineering'],
    ranking: 20,
    entranceExams: ['CUET', 'Christ entrance'],
    avgFees: { min: 100000, max: 300000 },
    avgPlacement: { min: 400000, max: 1000000 },
    website: 'https://www.christuniversity.in',
    highlights: ['Top deemed university', 'Strict yet supportive culture', 'Strong BBA and BCom programs', 'Bangalore location'],
  },
  {
    id: 'symbiosis-pune',
    name: 'Symbiosis International University',
    type: 'Deemed',
    city: 'Pune',
    state: 'Maharashtra',
    streams: ['Management', 'Law', 'Engineering', 'Design', 'Arts', 'Medical'],
    ranking: 22,
    entranceExams: ['SET (Symbiosis Entrance Test)'],
    avgFees: { min: 200000, max: 500000 },
    avgPlacement: { min: 600000, max: 1400000 },
    website: 'https://www.siu.edu.in',
    highlights: ['Strong law and management schools', 'International student community', 'Multiple specialized institutes'],
  },
  {
    id: 'thapar',
    name: 'Thapar Institute of Engineering',
    type: 'Deemed',
    city: 'Patiala',
    state: 'Punjab',
    streams: ['Engineering', 'Science', 'Management'],
    ranking: 33,
    entranceExams: ['JEE Main', 'Board marks'],
    avgFees: { min: 250000, max: 350000 },
    avgPlacement: { min: 600000, max: 1400000 },
    website: 'https://www.thapar.edu',
    highlights: ['Top private engineering in North', 'Strong CS and EE programs', 'Good placement track record'],
  },
  {
    id: 'iist',
    name: 'Indian Institute of Space Science and Technology',
    type: 'Autonomous',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    streams: ['Engineering', 'Science'],
    ranking: 29,
    entranceExams: ['JEE Advanced'],
    avgFees: { min: 50000, max: 100000 },
    avgPlacement: { min: 800000, max: 1500000 },
    website: 'https://www.iist.ac.in',
    highlights: ['Only space university', 'ISRO direct recruitment', 'Aerospace and avionics focus', 'Highly selective'],
  },
  {
    id: 'iiser-pune',
    name: 'IISER Pune',
    type: 'Autonomous',
    city: 'Pune',
    state: 'Maharashtra',
    streams: ['Science'],
    ranking: 12,
    entranceExams: ['IAT', 'JEE Advanced', 'KVPY'],
    avgFees: { min: 50000, max: 100000 },
    avgPlacement: { min: 500000, max: 1200000 },
    website: 'https://www.iiserpune.ac.in',
    highlights: ['Top science institute', 'BS-MS integrated program', 'Research from day one', 'Strong faculty'],
  },
  {
    id: 'iiser-kolkata',
    name: 'IISER Kolkata',
    type: 'Autonomous',
    city: 'Kolkata',
    state: 'West Bengal',
    streams: ['Science'],
    ranking: 18,
    entranceExams: ['IAT', 'JEE Advanced', 'KVPY'],
    avgFees: { min: 50000, max: 100000 },
    avgPlacement: { min: 500000, max: 1000000 },
    website: 'https://www.iiserkol.ac.in',
    highlights: ['Excellent research output', 'BS-MS program', 'Strong chemistry and biology departments'],
  },

  // === More Private/Deemed ===
  {
    id: 'amity',
    name: 'Amity University',
    type: 'Private',
    city: 'Noida',
    state: 'Uttar Pradesh',
    streams: ['Engineering', 'Management', 'Law', 'Arts', 'Medical', 'Design'],
    ranking: 32,
    entranceExams: ['Amity JEE', 'CUET'],
    avgFees: { min: 200000, max: 500000 },
    avgPlacement: { min: 400000, max: 900000 },
    website: 'https://www.amity.edu',
    highlights: ['Largest private university', 'Multiple campuses globally', 'Wide course variety', 'Industry partnerships'],
  },
  {
    id: 'lovely-professional',
    name: 'Lovely Professional University',
    type: 'Private',
    city: 'Phagwara',
    state: 'Punjab',
    streams: ['Engineering', 'Management', 'Arts', 'Science', 'Design', 'Law'],
    ranking: 40,
    entranceExams: ['LPUNEST', 'JEE Main'],
    avgFees: { min: 150000, max: 350000 },
    avgPlacement: { min: 400000, max: 800000 },
    website: 'https://www.lpu.in',
    highlights: ['Massive campus', 'Wide range of programs', 'International collaborations', 'One of the largest universities'],
  },
  {
    id: 'shiv-nadar',
    name: 'Shiv Nadar University',
    type: 'Private',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    streams: ['Engineering', 'Science', 'Arts', 'Management'],
    ranking: 34,
    entranceExams: ['SNUSAT', 'JEE Main'],
    avgFees: { min: 400000, max: 600000 },
    avgPlacement: { min: 600000, max: 1400000 },
    website: 'https://www.snusat.ac.in',
    highlights: ['Research-focused', 'Multidisciplinary approach', 'State-of-the-art campus', 'HCL founder\'s initiative'],
  },
  {
    id: 'plaksha',
    name: 'Plaksha University',
    type: 'Private',
    city: 'Mohali',
    state: 'Punjab',
    streams: ['Engineering', 'Science'],
    ranking: 50,
    entranceExams: ['Plaksha entrance', 'JEE Main'],
    avgFees: { min: 600000, max: 800000 },
    avgPlacement: { min: 800000, max: 1800000 },
    website: 'https://www.plaksha.edu.in',
    highlights: ['New-age tech university', 'Silicon Valley-style education', 'Problem-driven learning', 'Strong industry mentors'],
  },
  {
    id: 'flame',
    name: 'FLAME University',
    type: 'Private',
    city: 'Pune',
    state: 'Maharashtra',
    streams: ['Arts', 'Science', 'Commerce', 'Design'],
    ranking: 58,
    entranceExams: ['FLAME entrance'],
    avgFees: { min: 600000, max: 800000 },
    avgPlacement: { min: 400000, max: 1000000 },
    website: 'https://www.flame.edu.in',
    highlights: ['Liberal education model', 'Small class sizes', 'Interdisciplinary approach', 'Pune campus'],
  },
  {
    id: 'krea',
    name: 'Krea University',
    type: 'Private',
    city: 'Sri City',
    state: 'Andhra Pradesh',
    streams: ['Arts', 'Science', 'Social Sciences'],
    ranking: 55,
    entranceExams: ['Krea entrance'],
    avgFees: { min: 700000, max: 900000 },
    avgPlacement: { min: 500000, max: 1100000 },
    website: 'https://www.krea.edu.in',
    highlights: ['Interwoven learning approach', 'IFMR (finance) integration', 'Liberal arts and sciences'],
  },
  {
    id: 'coep-pune',
    name: 'COEP Technological University',
    type: 'Autonomous',
    city: 'Pune',
    state: 'Maharashtra',
    streams: ['Engineering'],
    ranking: 31,
    entranceExams: ['MHT-CET', 'JEE Main'],
    avgFees: { min: 100000, max: 180000 },
    avgPlacement: { min: 600000, max: 1300000 },
    website: 'https://www.coep.org.in',
    highlights: ['Oldest engineering college in Asia (1854)', 'Strong alumni network', 'BAJA SAE champions', 'Affordable education'],
  },
  {
    id: 'rvce-bangalore',
    name: 'RV College of Engineering',
    type: 'Autonomous',
    city: 'Bangalore',
    state: 'Karnataka',
    streams: ['Engineering'],
    ranking: 37,
    entranceExams: ['KCET', 'COMEDK'],
    avgFees: { min: 200000, max: 350000 },
    avgPlacement: { min: 600000, max: 1300000 },
    website: 'https://www.rvce.edu.in',
    highlights: ['Top Bangalore engineering college', 'Strong placement record', 'Good infrastructure'],
  },
  {
    id: 'pes-bangalore',
    name: 'PES University',
    type: 'Private',
    city: 'Bangalore',
    state: 'Karnataka',
    streams: ['Engineering', 'Science', 'Management', 'Design'],
    ranking: 44,
    entranceExams: ['PESSAT', 'KCET'],
    avgFees: { min: 300000, max: 500000 },
    avgPlacement: { min: 600000, max: 1500000 },
    website: 'https://www.pes.edu',
    highlights: ['Strong CS programs', 'Good startup culture', 'Bangalore tech ecosystem', 'Research focus'],
  },
  {
    id: 'iisc-bangalore',
    name: 'Indian Institute of Science',
    type: 'Autonomous',
    city: 'Bangalore',
    state: 'Karnataka',
    streams: ['Science', 'Engineering'],
    ranking: 1,
    entranceExams: ['JEE Advanced', 'GATE', 'KVPY', 'JAM'],
    avgFees: { min: 25000, max: 50000 },
    avgPlacement: { min: 1000000, max: 2500000 },
    website: 'https://www.iisc.ac.in',
    highlights: ['Best research institute in India', 'BS program for undergrads', 'World-class labs', 'Low fees, high research output'],
  },
  {
    id: 'jadavpur',
    name: 'Jadavpur University',
    type: 'State University',
    city: 'Kolkata',
    state: 'West Bengal',
    streams: ['Engineering', 'Arts', 'Science'],
    ranking: 16,
    entranceExams: ['WBJEE', 'CUET'],
    avgFees: { min: 10000, max: 30000 },
    avgPlacement: { min: 500000, max: 1200000 },
    website: 'https://www.jaduniv.edu.in',
    highlights: ['Top state university for engineering', 'Very affordable', 'Strong technical heritage', 'Film studies program'],
  },
  {
    id: 'anna-university',
    name: 'Anna University',
    type: 'State University',
    city: 'Chennai',
    state: 'Tamil Nadu',
    streams: ['Engineering', 'Science', 'Architecture'],
    ranking: 14,
    entranceExams: ['TNEA', 'GATE'],
    avgFees: { min: 50000, max: 100000 },
    avgPlacement: { min: 500000, max: 1100000 },
    website: 'https://www.annauniv.edu',
    highlights: ['Top state technical university', 'Guindy campus', 'Affiliated to 500+ colleges', 'Strong engineering tradition'],
  },
  {
    id: 'savitribai-phule',
    name: 'Savitribai Phule Pune University',
    type: 'State University',
    city: 'Pune',
    state: 'Maharashtra',
    streams: ['Arts', 'Science', 'Commerce', 'Engineering', 'Law'],
    ranking: 10,
    entranceExams: ['CUET', 'University entrance'],
    avgFees: { min: 10000, max: 30000 },
    avgPlacement: { min: 400000, max: 900000 },
    website: 'https://www.unipune.ac.in',
    highlights: ['Major Pune university', 'Wide range of courses', 'Research intensive', 'Beautiful campus'],
  },
  {
    id: 'dtu',
    name: 'Delhi Technological University',
    type: 'State University',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Engineering', 'Management'],
    ranking: 32,
    entranceExams: ['JEE Main', 'JAC Delhi'],
    avgFees: { min: 150000, max: 200000 },
    avgPlacement: { min: 800000, max: 1800000 },
    website: 'https://www.dtu.ac.in',
    highlights: ['Former DCE', 'Strong placements', 'Delhi location advantage', 'Good startup ecosystem'],
  },
  {
    id: 'nsut',
    name: 'Netaji Subhas University of Technology',
    type: 'State University',
    city: 'New Delhi',
    state: 'Delhi',
    streams: ['Engineering', 'Management'],
    ranking: 39,
    entranceExams: ['JEE Main', 'JAC Delhi'],
    avgFees: { min: 150000, max: 200000 },
    avgPlacement: { min: 700000, max: 1600000 },
    website: 'https://www.nsut.ac.in',
    highlights: ['Former NSIT', 'Strong CS and IT', 'Delhi tech hub', 'Competitive admissions'],
  },
  {
    id: 'ict-mumbai',
    name: 'Institute of Chemical Technology, Mumbai',
    type: 'Autonomous',
    city: 'Mumbai',
    state: 'Maharashtra',
    streams: ['Engineering', 'Science', 'Pharmacy'],
    ranking: 16,
    entranceExams: ['MHT-CET', 'JEE Main'],
    avgFees: { min: 80000, max: 150000 },
    avgPlacement: { min: 700000, max: 1500000 },
    website: 'https://www.ictmumbai.edu.in',
    highlights: ['Best for chemical engineering', 'Pharmacy programs', 'UDCT heritage', 'Industry connections'],
  },
  {
    id: 'ism-pune',
    name: 'Symbiosis Centre for Management Studies',
    type: 'Deemed',
    city: 'Pune',
    state: 'Maharashtra',
    streams: ['Management'],
    ranking: 15,
    entranceExams: ['SNAP'],
    avgFees: { min: 400000, max: 600000 },
    avgPlacement: { min: 800000, max: 1600000 },
    website: 'https://www.scmspune.ac.in',
    highlights: ['Top MBA outside IIMs', 'Strong marketing placements', 'Pune corporate hub'],
  },
  {
    id: 'xlri-jamshedpur',
    name: 'XLRI Jamshedpur',
    type: 'Private',
    city: 'Jamshedpur',
    state: 'Jharkhand',
    streams: ['Management'],
    ranking: 7,
    entranceExams: ['XAT'],
    avgFees: { min: 2500000, max: 2800000 },
    avgPlacement: { min: 2500000, max: 3800000 },
    website: 'https://www.xlri.ac.in',
    highlights: ['Best HR program in India', 'Jesuit values', 'Top 10 B-school', 'Strong corporate connections'],
  },
  {
    id: 'sp-jain',
    name: 'SP Jain Institute of Management & Research',
    type: 'Autonomous',
    city: 'Mumbai',
    state: 'Maharashtra',
    streams: ['Management'],
    ranking: 10,
    entranceExams: ['CAT', 'XAT'],
    avgFees: { min: 1800000, max: 2200000 },
    avgPlacement: { min: 2000000, max: 3200000 },
    website: 'https://www.spjimr.org',
    highlights: ['Top 10 B-school', 'ABGP social immersion', 'Mumbai corporate advantage', 'Design thinking focus'],
  },
  {
    id: 'nmims-mumbai',
    name: 'NMIMS Mumbai',
    type: 'Deemed',
    city: 'Mumbai',
    state: 'Maharashtra',
    streams: ['Management', 'Engineering', 'Pharmacy', 'Commerce', 'Law'],
    ranking: 12,
    entranceExams: ['NMAT'],
    avgFees: { min: 400000, max: 1000000 },
    avgPlacement: { min: 800000, max: 1800000 },
    website: 'https://www.nmims.edu',
    highlights: ['Strong MBA program', 'Mumbai location', 'Narsee Monjee legacy', 'Multiple campuses'],
  },
  {
    id: 'snu-greater-noida',
    name: 'Sharda University',
    type: 'Private',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    streams: ['Engineering', 'Medical', 'Management', 'Law', 'Arts'],
    ranking: 62,
    entranceExams: ['University entrance', 'CUET'],
    avgFees: { min: 150000, max: 350000 },
    avgPlacement: { min: 400000, max: 800000 },
    website: 'https://www.sharda.ac.in',
    highlights: ['International student body', 'Wide range of programs', 'NCR location', 'Medical college included'],
  },
  {
    id: 'chandigarh-university',
    name: 'Chandigarh University',
    type: 'Private',
    city: 'Mohali',
    state: 'Punjab',
    streams: ['Engineering', 'Management', 'Law', 'Arts', 'Science', 'Design'],
    ranking: 28,
    entranceExams: ['CUCET', 'JEE Main'],
    avgFees: { min: 150000, max: 350000 },
    avgPlacement: { min: 500000, max: 1000000 },
    website: 'https://www.cuchd.in',
    highlights: ['Fast-growing private university', 'Patent filing record', 'Strong placement cell', 'Modern campus'],
  },
  {
    id: 'presidency-kolkata',
    name: 'Presidency University, Kolkata',
    type: 'State University',
    city: 'Kolkata',
    state: 'West Bengal',
    streams: ['Arts', 'Science'],
    ranking: 25,
    entranceExams: ['University entrance'],
    avgFees: { min: 5000, max: 15000 },
    avgPlacement: { min: 300000, max: 700000 },
    website: 'https://www.presiuniv.ac.in',
    highlights: ['Heritage institution (1817)', 'Strong sciences', 'Notable alumni in politics and academia', 'Affordable education'],
  },
  {
    id: 'fergusson-pune',
    name: 'Fergusson College, Pune',
    type: 'Autonomous',
    city: 'Pune',
    state: 'Maharashtra',
    streams: ['Arts', 'Science'],
    ranking: 35,
    entranceExams: ['CUET', 'College entrance'],
    avgFees: { min: 20000, max: 50000 },
    avgPlacement: { min: 300000, max: 700000 },
    website: 'https://www.fergusson.edu',
    highlights: ['Heritage college (1885)', 'Strong sciences', 'Beautiful campus', 'Research culture'],
  },
  {
    id: 'loyola-chennai',
    name: 'Loyola College, Chennai',
    type: 'Autonomous',
    city: 'Chennai',
    state: 'Tamil Nadu',
    streams: ['Arts', 'Science', 'Commerce'],
    ranking: 8,
    entranceExams: ['CUET', 'College entrance'],
    avgFees: { min: 20000, max: 50000 },
    avgPlacement: { min: 400000, max: 900000 },
    website: 'https://www.loyolacollege.edu',
    highlights: ['Top South Indian college', 'Jesuit institution', 'Strong economics and commerce', 'A++ NAAC grade'],
  },
  {
    id: 'xaviers-mumbai',
    name: "St. Xavier's College, Mumbai",
    type: 'Autonomous',
    city: 'Mumbai',
    state: 'Maharashtra',
    streams: ['Arts', 'Science', 'Commerce'],
    ranking: 6,
    entranceExams: ['CUET', 'Xavier entrance'],
    avgFees: { min: 15000, max: 40000 },
    avgPlacement: { min: 400000, max: 1000000 },
    website: 'https://www.xaviers.edu',
    highlights: ['Iconic Mumbai college', 'Malhar festival', 'Strong BMM program', 'Heritage campus'],
  },
  {
    id: 'mit-manipal',
    name: 'Manipal Institute of Technology',
    type: 'Deemed',
    city: 'Manipal',
    state: 'Karnataka',
    streams: ['Engineering'],
    ranking: 26,
    entranceExams: ['MET'],
    avgFees: { min: 300000, max: 450000 },
    avgPlacement: { min: 600000, max: 1400000 },
    website: 'https://www.manipal.edu/mit.html',
    highlights: ['Top private engineering college', 'Campus town experience', 'Strong alumni', 'International exposure'],
  },
];

export const collegeTypes = ['IIT', 'NIT', 'IIIT', 'Central University', 'State University', 'Private', 'Deemed', 'Autonomous'] as const;

export const allStreams = [
  'Engineering', 'Medical', 'Science', 'Commerce', 'Arts', 'Management',
  'Design', 'Law', 'Architecture', 'Fashion', 'Pharmacy', 'Agriculture',
  'Social Sciences', 'Languages', 'Education', 'Mining', 'Nursing',
  'Liberal Arts', 'Economics', 'Public Policy',
];

export const indianStates = [
  'Andhra Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Delhi', 'Goa',
  'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Puducherry',
  'Punjab', 'Rajasthan', 'Tamil Nadu', 'Telangana', 'Uttar Pradesh',
  'Uttarakhand', 'West Bengal', 'Jammu & Kashmir',
];
