export interface Exam {
  id: string;
  name: string;
  fullName: string;
  streams: string[];
  eligibility: string;
  examMonth: string;
  difficulty: 'High' | 'Medium' | 'Low';
  acceptedBy: string;
  registrationUrl?: string;
  tips: string;
}

export const exams: Exam[] = [
  // === Engineering ===
  {
    id: 'jee-main',
    name: 'JEE Main',
    fullName: 'Joint Entrance Examination Main',
    streams: ['Engineering', 'Architecture'],
    eligibility: 'Class 12 passed or appearing with Physics, Chemistry, Maths. Age: no limit. Max 3 consecutive attempts.',
    examMonth: 'January & April',
    difficulty: 'High',
    acceptedBy: '31 NITs, 26 IIITs, and other centrally funded technical institutions',
    registrationUrl: 'https://jeemain.nta.nic.in',
    tips: 'Focus on NCERT for basics, then solve previous year papers. Time management is crucial. Practice mock tests weekly.',
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    fullName: 'Joint Entrance Examination Advanced',
    streams: ['Engineering', 'Science'],
    eligibility: 'Must qualify JEE Main (top 2.5 lakh). Class 12 with 75% aggregate (65% for SC/ST). Max 2 attempts in consecutive years.',
    examMonth: 'May/June',
    difficulty: 'High',
    acceptedBy: '23 IITs, IIST, IISER (partial)',
    registrationUrl: 'https://jeeadv.ac.in',
    tips: 'Deep conceptual understanding needed. Practice numerical problems extensively. Focus on problem-solving speed and accuracy.',
  },
  {
    id: 'bitsat',
    name: 'BITSAT',
    fullName: 'Birla Institute of Technology and Science Admission Test',
    streams: ['Engineering', 'Pharmacy', 'Science'],
    eligibility: 'Class 12 with 75% aggregate and 60% in PCM. First attempt only.',
    examMonth: 'May/June',
    difficulty: 'High',
    acceptedBy: 'BITS Pilani, Goa, Hyderabad, and Dubai campuses',
    registrationUrl: 'https://www.bitsadmission.com',
    tips: 'Speed matters most. Practice for accuracy under time pressure. English and Logical Reasoning sections can boost your score.',
  },
  {
    id: 'viteee',
    name: 'VITEEE',
    fullName: 'VIT Engineering Entrance Examination',
    streams: ['Engineering'],
    eligibility: 'Class 12 with 60% aggregate in PCM/PCB. No age limit.',
    examMonth: 'April/May',
    difficulty: 'Medium',
    acceptedBy: 'VIT Vellore, Chennai, AP, and Bhopal campuses',
    registrationUrl: 'https://viteee.vit.ac.in',
    tips: 'Moderate difficulty. Focus on NCERT concepts and practice aptitude. Consistent preparation over 3-4 months is sufficient.',
  },
  {
    id: 'srmjeee',
    name: 'SRMJEEE',
    fullName: 'SRM Joint Engineering Entrance Examination',
    streams: ['Engineering'],
    eligibility: 'Class 12 with 50% aggregate in PCM/PCB.',
    examMonth: 'April/May',
    difficulty: 'Medium',
    acceptedBy: 'SRM Institute of Science and Technology, all campuses',
    registrationUrl: 'https://www.srmist.edu.in',
    tips: 'Moderate difficulty. Focus on basics from NCERT. Practice previous year question papers for pattern familiarity.',
  },
  {
    id: 'comedk',
    name: 'COMEDK UGET',
    fullName: 'Consortium of Medical, Engineering and Dental Colleges of Karnataka Under Graduate Entrance Test',
    streams: ['Engineering'],
    eligibility: 'Class 12 with PCM, minimum 45% aggregate (40% for SC/ST).',
    examMonth: 'May',
    difficulty: 'Medium',
    acceptedBy: 'Over 190 engineering colleges in Karnataka',
    registrationUrl: 'https://www.comedk.org',
    tips: 'Similar to JEE Main but slightly easier. Focus on state board syllabus along with NCERT. Good option for Karnataka colleges.',
  },
  {
    id: 'mht-cet',
    name: 'MHT-CET',
    fullName: 'Maharashtra Common Entrance Test',
    streams: ['Engineering', 'Pharmacy'],
    eligibility: 'Class 12 with PCM/PCB. Maharashtra domicile preferred.',
    examMonth: 'May',
    difficulty: 'Medium',
    acceptedBy: 'All engineering and pharmacy colleges in Maharashtra',
    registrationUrl: 'https://cetcell.mahacet.org',
    tips: 'Based on Maharashtra state board and NCERT. Practice numerical problems. Chemistry and Maths carry more weight.',
  },
  {
    id: 'kcet',
    name: 'KCET',
    fullName: 'Karnataka Common Entrance Test',
    streams: ['Engineering', 'Medical', 'Agriculture'],
    eligibility: 'Class 12 with relevant subjects. Karnataka domicile for state quota.',
    examMonth: 'April/May',
    difficulty: 'Medium',
    acceptedBy: 'All government and private colleges in Karnataka for engineering and medical',
    registrationUrl: 'https://cetonline.karnataka.gov.in',
    tips: 'Based on PUC-II syllabus. Practice state board textbooks thoroughly. Easier than JEE Main.',
  },
  {
    id: 'wbjee',
    name: 'WBJEE',
    fullName: 'West Bengal Joint Entrance Examination',
    streams: ['Engineering', 'Pharmacy', 'Architecture'],
    eligibility: 'Class 12 with PCM. West Bengal domicile for state quota.',
    examMonth: 'April/May',
    difficulty: 'Medium',
    acceptedBy: 'Jadavpur University, all state engineering colleges in West Bengal',
    registrationUrl: 'https://wbjeeb.nic.in',
    tips: 'Moderate difficulty. Strong focus on Class 11 and 12 concepts. Jadavpur University is the top prize.',
  },
  {
    id: 'ipu-cet',
    name: 'IPU CET',
    fullName: 'Indraprastha University Common Entrance Test',
    streams: ['Engineering', 'Management', 'Law', 'Medical'],
    eligibility: 'Class 12 passed. Delhi domicile for some quotas.',
    examMonth: 'May/June',
    difficulty: 'Medium',
    acceptedBy: 'All colleges affiliated to GGSIPU Delhi',
    registrationUrl: 'https://ipu.ac.in',
    tips: 'Cover NCERT thoroughly. Moderate difficulty. Good option for Delhi-based students as a backup.',
  },
  {
    id: 'met',
    name: 'MET',
    fullName: 'Manipal Entrance Test',
    streams: ['Engineering', 'Medical', 'Management', 'Design'],
    eligibility: 'Class 12 with 50% in relevant subjects.',
    examMonth: 'April/May',
    difficulty: 'Medium',
    acceptedBy: 'Manipal Academy of Higher Education, all campuses',
    registrationUrl: 'https://www.manipal.edu',
    tips: 'Moderate difficulty. Focus on NCERT and solve Manipal previous papers. General knowledge section included.',
  },

  // === Medical ===
  {
    id: 'neet-ug',
    name: 'NEET UG',
    fullName: 'National Eligibility cum Entrance Test (Undergraduate)',
    streams: ['Medical', 'Dental'],
    eligibility: 'Class 12 with PCB, minimum 50% aggregate (40% for SC/ST/OBC). Age: 17-25 years.',
    examMonth: 'May',
    difficulty: 'High',
    acceptedBy: 'All medical and dental colleges in India including AIIMS, JIPMER, state colleges',
    registrationUrl: 'https://neet.nta.nic.in',
    tips: 'NCERT is the bible for NEET. Biology has maximum weightage. Practice MCQs daily. Revision is key.',
  },
  {
    id: 'neet-pg',
    name: 'NEET PG',
    fullName: 'National Eligibility cum Entrance Test (Postgraduate)',
    streams: ['Medical'],
    eligibility: 'MBBS degree with internship completion.',
    examMonth: 'March',
    difficulty: 'High',
    acceptedBy: 'All MD/MS/PG Diploma programs in India',
    registrationUrl: 'https://nbe.edu.in',
    tips: 'Use standard PG prep resources. Focus on high-yield topics. Clinical exposure helps in answering.',
  },
  {
    id: 'ini-cet',
    name: 'INI-CET',
    fullName: 'Institute of National Importance Combined Entrance Test',
    streams: ['Medical'],
    eligibility: 'MBBS degree with internship completion.',
    examMonth: 'May & November',
    difficulty: 'High',
    acceptedBy: 'AIIMS, JIPMER, NIMHANS, PGIMER, and other INIs',
    registrationUrl: 'https://aiimsexams.ac.in',
    tips: 'Higher difficulty than NEET PG. Focus on conceptual understanding and clinical reasoning.',
  },

  // === Law ===
  {
    id: 'clat',
    name: 'CLAT',
    fullName: 'Common Law Admission Test',
    streams: ['Law'],
    eligibility: 'Class 12 passed with 45% (40% for SC/ST). Age: no upper limit for UG.',
    examMonth: 'December',
    difficulty: 'High',
    acceptedBy: '22 National Law Universities across India',
    registrationUrl: 'https://consortiumofnlus.ac.in',
    tips: 'Reading comprehension is key. Practice legal reasoning daily. Current affairs from last 12 months. Solve full-length mocks.',
  },
  {
    id: 'ailet',
    name: 'AILET',
    fullName: 'All India Law Entrance Test',
    streams: ['Law'],
    eligibility: 'Class 12 passed with 50%.',
    examMonth: 'June',
    difficulty: 'High',
    acceptedBy: 'NLU Delhi',
    registrationUrl: 'https://nludelhi.ac.in',
    tips: 'Tougher than CLAT for GK section. Extensive current affairs preparation needed. Legal aptitude focus.',
  },
  {
    id: 'lsat-india',
    name: 'LSAT India',
    fullName: 'Law School Admission Test India',
    streams: ['Law'],
    eligibility: 'Class 12 passed or appearing.',
    examMonth: 'January & June',
    difficulty: 'Medium',
    acceptedBy: 'Jindal Global Law School, and 90+ colleges across India',
    registrationUrl: 'https://www.lsatindia.in',
    tips: 'Focus on analytical and logical reasoning. Reading comprehension heavy. No GK section unlike CLAT.',
  },

  // === Design ===
  {
    id: 'nid-dat',
    name: 'NID DAT',
    fullName: 'National Institute of Design Design Aptitude Test',
    streams: ['Design'],
    eligibility: 'Class 12 passed from any stream.',
    examMonth: 'January',
    difficulty: 'High',
    acceptedBy: 'NID Ahmedabad, Gandhinagar, Haryana, Assam, Madhya Pradesh campuses',
    registrationUrl: 'https://admissions.nid.edu',
    tips: 'Build a strong drawing and observation habit. Study design thinking. Practice situation tests. Portfolio preparation important for studio test.',
  },
  {
    id: 'nift-entrance',
    name: 'NIFT Entrance',
    fullName: 'National Institute of Fashion Technology Entrance Exam',
    streams: ['Design', 'Fashion'],
    eligibility: 'Class 12 passed from any stream.',
    examMonth: 'February',
    difficulty: 'Medium',
    acceptedBy: 'All 18 NIFT campuses across India',
    registrationUrl: 'https://www.nift.ac.in',
    tips: 'Creative ability test (CAT) and General Ability Test (GAT). Practice sketching and creative thinking. Follow fashion trends.',
  },
  {
    id: 'nata',
    name: 'NATA',
    fullName: 'National Aptitude Test in Architecture',
    streams: ['Architecture'],
    eligibility: 'Class 12 with Mathematics, minimum 50% aggregate.',
    examMonth: 'April',
    difficulty: 'Medium',
    acceptedBy: 'All architecture colleges in India (government and private)',
    registrationUrl: 'https://www.nata.in',
    tips: 'Practice architectural drawing. Strong mathematics foundation needed. Aesthetic sensitivity and observation skills matter.',
  },
  {
    id: 'uceed',
    name: 'UCEED',
    fullName: 'Undergraduate Common Entrance Exam for Design',
    streams: ['Design'],
    eligibility: 'Class 12 passed or appearing. Max 3 attempts.',
    examMonth: 'January',
    difficulty: 'High',
    acceptedBy: 'IIT Bombay (IDC), IIT Guwahati, IIT Hyderabad, IIITDM Jabalpur',
    registrationUrl: 'https://www.uceed.iitb.ac.in',
    tips: 'Focus on observation, visualization, and design aptitude. Practice drawing skills. Study product and visual design concepts.',
  },
  {
    id: 'ceed',
    name: 'CEED',
    fullName: 'Common Entrance Exam for Design (PG)',
    streams: ['Design'],
    eligibility: 'Graduates in any discipline.',
    examMonth: 'January',
    difficulty: 'High',
    acceptedBy: 'IIT Bombay, IIT Delhi, IIT Guwahati, IIT Hyderabad, IISc Bangalore',
    registrationUrl: 'https://www.ceed.iitb.ac.in',
    tips: 'Strong portfolio needed. Part A is screening, Part B is subjective. Study design history and contemporary practices.',
  },

  // === Common University ===
  {
    id: 'cuet',
    name: 'CUET UG',
    fullName: 'Common University Entrance Test (Undergraduate)',
    streams: ['Arts', 'Science', 'Commerce', 'Social Sciences'],
    eligibility: 'Class 12 passed or appearing from any recognized board.',
    examMonth: 'May/June',
    difficulty: 'Medium',
    acceptedBy: '260+ central, state, deemed, and private universities including DU, JNU, BHU, Jamia',
    registrationUrl: 'https://cuet.samarth.ac.in',
    tips: 'NCERT-based questions. Focus on domain subjects and general test. Time management across multiple sections is crucial.',
  },
  {
    id: 'cuet-pg',
    name: 'CUET PG',
    fullName: 'Common University Entrance Test (Postgraduate)',
    streams: ['Arts', 'Science', 'Commerce', 'Social Sciences'],
    eligibility: 'Graduates in relevant discipline.',
    examMonth: 'June/July',
    difficulty: 'Medium',
    acceptedBy: 'Central universities for MA, MSc, MCom, and other PG programs',
    registrationUrl: 'https://cuet.samarth.ac.in',
    tips: 'Focus on domain knowledge. Previous year papers are very helpful. NCERT+ level preparation.',
  },

  // === Management ===
  {
    id: 'cat',
    name: 'CAT',
    fullName: 'Common Admission Test',
    streams: ['Management'],
    eligibility: 'Graduates with 50% (45% for SC/ST). Final year students can apply.',
    examMonth: 'November',
    difficulty: 'High',
    acceptedBy: '20 IIMs and 1200+ B-schools across India',
    registrationUrl: 'https://iimcat.ac.in',
    tips: 'VARC, DILR, and QA sections. Practice time management. Mock tests are essential. Focus on accuracy over attempts.',
  },
  {
    id: 'xat',
    name: 'XAT',
    fullName: 'Xavier Aptitude Test',
    streams: ['Management'],
    eligibility: 'Graduates from any recognized university.',
    examMonth: 'January',
    difficulty: 'High',
    acceptedBy: 'XLRI Jamshedpur and 160+ B-schools',
    registrationUrl: 'https://xatonline.in',
    tips: 'Decision-making section is unique to XAT. Essay writing included. Prepare for ethical dilemma questions.',
  },
  {
    id: 'snap',
    name: 'SNAP',
    fullName: 'Symbiosis National Aptitude Test',
    streams: ['Management'],
    eligibility: 'Graduates with 50% (45% for SC/ST).',
    examMonth: 'December',
    difficulty: 'Medium',
    acceptedBy: 'All Symbiosis B-schools including SIBM, SCMS, SIIB',
    registrationUrl: 'https://www.snaptest.org',
    tips: 'Shorter exam than CAT. Speed is important. General English and current affairs carry significant weight.',
  },
  {
    id: 'nmat',
    name: 'NMAT',
    fullName: 'NMIMS Management Aptitude Test',
    streams: ['Management'],
    eligibility: 'Graduates from any recognized university.',
    examMonth: 'October-December',
    difficulty: 'Medium',
    acceptedBy: 'NMIMS Mumbai and other campuses, 30+ partner institutes',
    registrationUrl: 'https://www.nmat.org',
    tips: 'Flexible test window. Can retake up to 3 times. Focus on language skills and quantitative aptitude.',
  },
  {
    id: 'mat',
    name: 'MAT',
    fullName: 'Management Aptitude Test',
    streams: ['Management'],
    eligibility: 'Graduates from any recognized university.',
    examMonth: 'February, May, September, December',
    difficulty: 'Medium',
    acceptedBy: '600+ B-schools across India',
    registrationUrl: 'https://www.aima.in',
    tips: 'Conducted 4 times a year. Good for backup. Covers language, math, data analysis, intelligence, and Indian/global environment.',
  },
  {
    id: 'ipm-aptitude',
    name: 'IPMAT',
    fullName: 'Integrated Programme in Management Aptitude Test',
    streams: ['Management'],
    eligibility: 'Class 12 passed with 60% (55% for SC/ST). Age: max 20 years.',
    examMonth: 'May',
    difficulty: 'High',
    acceptedBy: 'IIM Indore, IIM Rohtak, IIM Ranchi, IIM Bodh Gaya, IIM Jammu for 5-year integrated program',
    registrationUrl: 'https://www.iimidr.ac.in',
    tips: 'Quantitative ability and verbal ability sections. SA and MCQ format. Start preparation from Class 11.',
  },

  // === Postgraduate Engineering / Research ===
  {
    id: 'gate',
    name: 'GATE',
    fullName: 'Graduate Aptitude Test in Engineering',
    streams: ['Engineering', 'Science'],
    eligibility: 'Graduates in engineering/technology/science or final year students.',
    examMonth: 'February',
    difficulty: 'High',
    acceptedBy: 'IITs, NITs, IISc for MTech/PhD. Also used by PSUs for recruitment.',
    registrationUrl: 'https://gate.iitb.ac.in',
    tips: 'Subject-specific preparation needed. Previous year papers are essential. Numerical answer type questions require accuracy.',
  },
  {
    id: 'jam',
    name: 'IIT JAM',
    fullName: 'Joint Admission Test for Masters',
    streams: ['Science'],
    eligibility: 'BSc graduates or final year students in relevant subjects.',
    examMonth: 'February',
    difficulty: 'High',
    acceptedBy: 'IITs, IISc, NITs for MSc programs',
    registrationUrl: 'https://jam.iitb.ac.in',
    tips: 'Focus on core subjects. Practice numerical and descriptive questions. Good for transition from BSc to IIT.',
  },

  // === Civil Services ===
  {
    id: 'upsc-cse',
    name: 'UPSC CSE',
    fullName: 'Union Public Service Commission Civil Services Examination',
    streams: ['Civil Services'],
    eligibility: 'Graduates from any discipline. Age: 21-32 years (relaxation for reserved categories). Max 6 attempts for General.',
    examMonth: 'May (Prelims), September (Mains)',
    difficulty: 'High',
    acceptedBy: 'IAS, IPS, IFS, IRS, and other Group A and B central services',
    registrationUrl: 'https://www.upsc.gov.in',
    tips: 'Long-term preparation needed (12-18 months minimum). NCERT foundation essential. Answer writing practice for Mains. Optional subject selection is crucial.',
  },

  // === Scholarships / Science ===
  {
    id: 'kvpy',
    name: 'KVPY',
    fullName: 'Kishore Vaigyanik Protsahan Yojana',
    streams: ['Science'],
    eligibility: 'Class 11 (SA), Class 12 (SX), or 1st year BSc (SB) students with 60% in science/math.',
    examMonth: 'November (now merged with INSPIRE)',
    difficulty: 'High',
    acceptedBy: 'IISc Bangalore, IISERs. Provides fellowship for BSc-PhD programs.',
    tips: 'Strong conceptual foundation in Physics, Chemistry, Biology, and Math needed. Focus on analytical thinking.',
  },
  {
    id: 'ntse',
    name: 'NTSE',
    fullName: 'National Talent Search Examination',
    streams: ['Science', 'Social Sciences'],
    eligibility: 'Class 10 students from recognized schools.',
    examMonth: 'November (Stage 1), May (Stage 2)',
    difficulty: 'High',
    acceptedBy: 'Scholarship program by NCERT. Monthly scholarship through graduation.',
    tips: 'MAT and SAT sections. Strong general knowledge and reasoning. Practice NCERT Class 9-10 thoroughly.',
  },
  {
    id: 'iat',
    name: 'IAT',
    fullName: 'IISER Aptitude Test',
    streams: ['Science'],
    eligibility: 'Class 12 with PCM/PCB. 60% aggregate.',
    examMonth: 'June',
    difficulty: 'High',
    acceptedBy: 'All 7 IISERs for BS-MS integrated program',
    registrationUrl: 'https://www.iiseradmission.in',
    tips: 'Conceptual questions in Physics, Chemistry, Maths, Biology. Focus on analytical thinking rather than formula-based approach.',
  },

  // === Other Important Exams ===
  {
    id: 'pessat',
    name: 'PESSAT',
    fullName: 'PES Scholastic Aptitude Test',
    streams: ['Engineering', 'Management', 'Design'],
    eligibility: 'Class 12 with PCM for engineering.',
    examMonth: 'January-April',
    difficulty: 'Medium',
    acceptedBy: 'PES University, Bangalore',
    registrationUrl: 'https://www.pes.edu',
    tips: 'Moderate difficulty. Focus on Physics, Chemistry, Math, and English. Practice aptitude questions.',
  },
  {
    id: 'lpunest',
    name: 'LPUNEST',
    fullName: 'LPU National Entrance and Scholarship Test',
    streams: ['Engineering', 'Management', 'Law', 'Design'],
    eligibility: 'Class 12 passed.',
    examMonth: 'January-May',
    difficulty: 'Low',
    acceptedBy: 'Lovely Professional University',
    registrationUrl: 'https://www.lpu.in',
    tips: 'Good score can earn scholarships. Based on NCERT syllabus. Moderate preparation sufficient.',
  },
  {
    id: 'jmi-entrance',
    name: 'JMI Entrance',
    fullName: 'Jamia Millia Islamia Entrance Examination',
    streams: ['Engineering', 'Arts', 'Architecture', 'Law', 'Education'],
    eligibility: 'Class 12 passed with relevant subjects.',
    examMonth: 'June/July',
    difficulty: 'Medium',
    acceptedBy: 'Jamia Millia Islamia for all programs',
    registrationUrl: 'https://www.jmi.ac.in',
    tips: 'University-specific exam. Focus on subject knowledge and general aptitude. Previous year papers are very helpful.',
  },
  {
    id: 'cucet',
    name: 'CUCET',
    fullName: 'Central Universities Common Entrance Test',
    streams: ['Arts', 'Science', 'Commerce', 'Engineering'],
    eligibility: 'Class 12 passed. Varies by program.',
    examMonth: 'May/June',
    difficulty: 'Medium',
    acceptedBy: 'Several central universities (now largely replaced by CUET)',
    registrationUrl: 'https://cucetexam.in',
    tips: 'Being merged with CUET. Check latest notifications. NCERT-based preparation.',
  },
  {
    id: 'tissnet',
    name: 'TISSNET',
    fullName: 'Tata Institute of Social Sciences National Entrance Test',
    streams: ['Social Sciences', 'Management'],
    eligibility: 'Graduates with 50% (45% for SC/ST).',
    examMonth: 'February',
    difficulty: 'Medium',
    acceptedBy: 'TISS Mumbai, Hyderabad, Guwahati, Tuljapur campuses',
    registrationUrl: 'https://www.tiss.edu',
    tips: 'Current affairs heavy. Social sensitivity questions. English proficiency and GK are key scoring areas.',
  },
  {
    id: 'cmat',
    name: 'CMAT',
    fullName: 'Common Management Admission Test',
    streams: ['Management'],
    eligibility: 'Graduates from any recognized university.',
    examMonth: 'January',
    difficulty: 'Medium',
    acceptedBy: 'JBIMS Mumbai, GIM Goa, KJ Somaiya, and 1000+ AICTE-approved institutions',
    registrationUrl: 'https://cmat.nta.nic.in',
    tips: 'Good alternative to CAT. Language, quant, logical reasoning, and GK sections. JBIMS is the top prize.',
  },
  {
    id: 'set',
    name: 'SET',
    fullName: 'Symbiosis Entrance Test',
    streams: ['Law', 'Arts', 'Engineering', 'Design'],
    eligibility: 'Class 12 passed or appearing.',
    examMonth: 'May',
    difficulty: 'Medium',
    acceptedBy: 'All Symbiosis International University institutes',
    registrationUrl: 'https://www.set-test.org',
    tips: 'General English, quantitative, and logical reasoning. Required for all Symbiosis UG programs. Moderate difficulty.',
  },
  {
    id: 'ap-eamcet',
    name: 'AP EAMCET',
    fullName: 'Andhra Pradesh Engineering, Agriculture and Medical Common Entrance Test',
    streams: ['Engineering', 'Medical', 'Agriculture'],
    eligibility: 'Class 12 with relevant subjects. AP/Telangana domicile preferred.',
    examMonth: 'May',
    difficulty: 'Medium',
    acceptedBy: 'All engineering, medical, and agriculture colleges in Andhra Pradesh',
    registrationUrl: 'https://cets.apsche.ap.gov.in',
    tips: 'State board syllabus based. 80% weightage from Class 12, 20% from Class 11. Practice intermediate-level problems.',
  },
  {
    id: 'ts-eamcet',
    name: 'TS EAMCET',
    fullName: 'Telangana State Engineering, Agriculture and Medical Common Entrance Test',
    streams: ['Engineering', 'Medical', 'Agriculture'],
    eligibility: 'Class 12 with relevant subjects. Telangana domicile preferred.',
    examMonth: 'May',
    difficulty: 'Medium',
    acceptedBy: 'All engineering, medical, and agriculture colleges in Telangana',
    registrationUrl: 'https://eamcet.tsche.ac.in',
    tips: 'Similar to AP EAMCET. Focus on Telangana state board syllabus. Good for state-level admissions.',
  },
  {
    id: 'keam',
    name: 'KEAM',
    fullName: 'Kerala Engineering Architecture Medical Entrance Exam',
    streams: ['Engineering', 'Architecture', 'Medical'],
    eligibility: 'Class 12 with relevant subjects. Kerala domicile.',
    examMonth: 'May',
    difficulty: 'Medium',
    acceptedBy: 'All engineering and architecture colleges in Kerala',
    registrationUrl: 'https://www.cee.kerala.gov.in',
    tips: 'Based on Kerala state board plus NCERT syllabus. Physics and Chemistry paper. Maths paper. Practice both.',
  },
];

export const examStreams = [
  'Engineering', 'Medical', 'Law', 'Design', 'Management', 'Science',
  'Architecture', 'Arts', 'Commerce', 'Social Sciences', 'Fashion',
  'Civil Services', 'Pharmacy', 'Agriculture', 'Dental',
];
