export interface Mentor {
  id: string;
  name: string;
  career: string;
  company: string;
  experience: string;
  city: string;
  bio: string;
  journey: string;
  advice: string;
  skills: string[];
  avatar: string;
  available: boolean;
  cluster: string;
}

export const mentors: Mentor[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    career: 'UX Designer',
    company: 'Google',
    experience: '8 years',
    city: 'Bangalore',
    bio: 'Lead UX Designer at Google working on Search and Maps products for India. Passionate about designing for the next billion users.',
    journey: 'Started with a BTech in Computer Science from NIT Trichy. Hated coding all day, but loved building interfaces. Taught myself design through YouTube and did freelance projects for 2 years. Got rejected from 40+ jobs before landing an internship at a Bangalore startup. Moved to Google after 3 years of grinding. The key was building a portfolio, not chasing degrees.',
    advice: 'Stop asking "what should I become?" and start asking "what problems do I love solving?" Your career will follow your curiosity.',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility'],
    avatar: 'P',
    available: true,
    cluster: 'Design & Creative',
  },
  {
    id: '2',
    name: 'Arjun Mehta',
    career: 'Data Scientist',
    company: 'Flipkart',
    experience: '6 years',
    city: 'Bangalore',
    bio: 'Senior Data Scientist at Flipkart building recommendation systems that serve 400M+ users. Previously at Amazon.',
    journey: 'Did BSc Statistics from St. Xavier\'s Mumbai because I couldn\'t get into engineering. Felt like a failure. Discovered Python and machine learning during lockdown. Did 50+ Kaggle competitions. Got into ISI Kolkata for MStat. Interned at Amazon, then joined Flipkart. My "failed" stats background turned out to be my biggest advantage.',
    advice: 'The world is drowning in data but starving for insight. Learn to tell stories with numbers and you\'ll never be unemployed.',
    skills: ['Python', 'Machine Learning', 'SQL', 'Statistics', 'Deep Learning'],
    avatar: 'A',
    available: true,
    cluster: 'Technology & AI',
  },
  {
    id: '3',
    name: 'Dr. Kavitha Rajan',
    career: 'Cardiologist',
    company: 'AIIMS Delhi',
    experience: '12 years',
    city: 'Delhi',
    bio: 'Associate Professor of Cardiology at AIIMS. Specializes in interventional cardiology and has performed 3000+ angioplasties.',
    journey: 'Grew up in a small town in Tamil Nadu. Failed NEET the first time. Took a gap year, studied 14 hours a day, got into JIPMER. MBBS took 5.5 years, MD took 3 more, DM Cardiology another 3. It was 12 years of training. Lost friends, missed weddings, questioned myself daily. But the first time I saved a heart attack patient, I knew every sacrifice was worth it.',
    advice: 'Medicine is not a career, it\'s a calling. If you can imagine doing anything else and being happy, do that instead. If you can\'t, welcome aboard.',
    skills: ['Clinical Skills', 'Research', 'Patient Communication', 'Leadership', 'Teaching'],
    avatar: 'K',
    available: false,
    cluster: 'Healthcare & Wellness',
  },
  {
    id: '4',
    name: 'Adv. Rohan Deshmukh',
    career: 'Supreme Court Lawyer',
    company: 'Supreme Court of India',
    experience: '15 years',
    city: 'Delhi',
    bio: 'Senior Advocate practicing constitutional law. Has argued 200+ cases including landmark privacy and free speech cases.',
    journey: 'Did BA History from Fergusson College, Pune. Everyone said I was wasting my potential. Did LLB from ILS, then LLM from NLU Delhi. First 3 years in Delhi, I earned less than an auto driver. Slept in a shared room with 4 people. Slowly built a reputation through pro bono work. Now I argue cases that shape the country\'s future.',
    advice: 'Law is the slowest profession to reward you and the most powerful once it does. If you choose this path, develop patience as your primary skill.',
    skills: ['Legal Research', 'Argumentation', 'Constitutional Law', 'Public Speaking', 'Writing'],
    avatar: 'R',
    available: true,
    cluster: 'Law & Governance',
  },
  {
    id: '5',
    name: 'Sneha Kulkarni',
    career: 'Content Creator',
    company: 'YouTube (2M+ subscribers)',
    experience: '5 years',
    city: 'Mumbai',
    bio: 'Full-time YouTuber creating educational content about science and technology in Hindi. Built a community of 2M+ curious learners.',
    journey: 'Engineering dropout from VIT. Parents were devastated. Started making YouTube videos about physics in my hostel room with a phone. First year: 200 subscribers. Kept going because I loved explaining things. Video about quantum physics went viral in Year 2. Quit my backup job at TCS. Now I run a team of 5 and earn more than most engineers in my batch.',
    advice: 'The internet is the greatest equalizer. You don\'t need a degree to teach, a studio to create, or permission to start. Just start.',
    skills: ['Storytelling', 'Video Production', 'Audience Building', 'Script Writing', 'Marketing'],
    avatar: 'S',
    available: true,
    cluster: 'Media & Entertainment',
  },
  {
    id: '6',
    name: 'Vikram Reddy',
    career: 'Startup Founder',
    company: 'UrbanKisan (Series B funded)',
    experience: '7 years',
    city: 'Hyderabad',
    bio: 'Founded UrbanKisan, an agritech startup that helps urban farms grow food sustainably. Raised $12M across rounds.',
    journey: 'IIT Madras CSE graduate. Joined McKinsey, felt empty inside. Spent weekends at organic farms. Quit McKinsey after 2 years (family thought I was insane). Built a prototype for smart urban farming in my apartment. First investor said no. Second said no. Twenty-third said yes. Now we have 10,000 farms across 8 cities.',
    advice: 'If your career plan doesn\'t scare you a little, it\'s not ambitious enough. The best careers are the ones you have to build yourself.',
    skills: ['Business Strategy', 'Fundraising', 'Team Building', 'Agriculture Tech', 'Leadership'],
    avatar: 'V',
    available: true,
    cluster: 'Business & Strategy',
  },
  {
    id: '7',
    name: 'Ananya Iyer',
    career: 'Architect',
    company: 'Studio Mumbai',
    experience: '10 years',
    city: 'Mumbai',
    bio: 'Principal Architect at Studio Mumbai. Designs sustainable buildings that blend traditional Indian techniques with modern architecture.',
    journey: 'Studied architecture at SPA Delhi. 5 years of college felt long but transformative. Worked at a small firm for terrible pay, then went to AA School London on a scholarship. Came back to India because I wanted to build here. Joined Studio Mumbai and fell in love with their philosophy of craft. Now I lead projects that have won international awards.',
    advice: 'Architecture is 90% patience and 10% creativity. If you love spaces, materials, and the way light enters a room, you might be one of us.',
    skills: ['Design Thinking', 'Sustainable Design', 'AutoCAD', 'Model Making', 'Client Management'],
    avatar: 'A',
    available: true,
    cluster: 'Design & Creative',
  },
  {
    id: '8',
    name: 'Kabir Singh Ahluwalia',
    career: 'AI Engineer',
    company: 'Microsoft Research',
    experience: '5 years',
    city: 'Bangalore',
    bio: 'Research Engineer at Microsoft working on AI for Indic languages. Published 12 papers on multilingual NLP.',
    journey: 'Middle-class family from Chandigarh. Did BTech from a tier-2 college (not IIT, not NIT). Professors said I wouldn\'t get into research. Applied to 30 MS programs, got into UMass Amherst with funding. Published my first paper in Year 1. Microsoft recruited me from a conference. The tier of your college matters way less than the quality of your curiosity.',
    advice: 'AI isn\'t just coding. It\'s about asking the right questions. The best AI engineers I know studied philosophy, linguistics, and psychology alongside engineering.',
    skills: ['Python', 'NLP', 'Deep Learning', 'Research', 'PyTorch'],
    avatar: 'K',
    available: true,
    cluster: 'Technology & AI',
  },
  {
    id: '9',
    name: 'Dr. Meera Nair',
    career: 'Clinical Psychologist',
    company: 'Private Practice',
    experience: '9 years',
    city: 'Kochi',
    bio: 'Clinical psychologist specializing in adolescent mental health. Runs a thriving private practice and trains school counselors across Kerala.',
    journey: 'Did BA Psychology from Christ University. Family wanted me to do MBA. Did MA Clinical Psychology from NIMHANS instead. MPhil took 2 more years. Started practice in a tiny room in Kochi. First month: 2 clients. Built trust slowly through workshops and word-of-mouth. Now I see 25 clients a week and train 100+ counselors annually. The wait was worth it.',
    advice: 'Mental health is the most important and most underserved field in India right now. If you have empathy and patience, we desperately need you.',
    skills: ['Therapy', 'Assessment', 'Training', 'Empathy', 'Research'],
    avatar: 'M',
    available: true,
    cluster: 'Healthcare & Wellness',
  },
  {
    id: '10',
    name: 'Ritu Agarwal IAS',
    career: 'IAS Officer',
    company: 'Government of India',
    experience: '11 years',
    city: 'Lucknow',
    bio: 'District Magistrate who transformed education outcomes in her district. Known for tech-driven governance innovations.',
    journey: 'Small-town girl from Gorakhpur. Did BA from Allahabad University. Failed UPSC twice. Third time, qualified with AIR 45. First posting in a remote district was a culture shock. Learned to navigate bureaucracy, politics, and public expectations. Now leading a district of 4 million people. Every day I see both the worst and best of India.',
    advice: 'Public service isn\'t about power. It\'s about responsibility. If you want to change India at scale, there\'s no substitute for being in the system.',
    skills: ['Administration', 'Policy Making', 'Public Communication', 'Crisis Management', 'Negotiation'],
    avatar: 'R',
    available: false,
    cluster: 'Government & Public Policy',
  },
  {
    id: '11',
    name: 'Zara Khan',
    career: 'Fashion Designer',
    company: 'Zara Khan Studios',
    experience: '8 years',
    city: 'Delhi',
    bio: 'Founder of her own fashion label blending traditional Indian textiles with contemporary silhouettes. Featured in Vogue India.',
    journey: 'Studied at NIFT Delhi. Parents were supportive but nervous about job prospects. Interned with Sabyasachi for 6 months and learned the business side. Worked at a fast-fashion brand for 2 years to save money. Launched my own label with Rs 3 lakh savings. First collection sold 12 pieces. Kept going. Now my brand does 2 crore annually and employs 30 artisans.',
    advice: 'Fashion isn\'t about trends. It\'s about identity, culture, and self-expression. Learn the craft deeply before chasing the glamour.',
    skills: ['Pattern Making', 'Textile Knowledge', 'Branding', 'Illustration', 'Business Management'],
    avatar: 'Z',
    available: true,
    cluster: 'Arts & Performance',
  },
  {
    id: '12',
    name: 'Aarav Joshi',
    career: 'Film Director',
    company: 'Independent',
    experience: '6 years',
    city: 'Mumbai',
    bio: 'Independent filmmaker whose debut film won the National Award for Best First Film. Now working on an OTT series for Netflix.',
    journey: 'BA English Literature from St. Stephen\'s. Worked as an AD (assistant director) for 3 years at pathetic wages. Wrote 7 screenplays, all rejected. Raised money from friends and family for my debut film. Shot in 21 days on a shoestring budget. The film won at MAMI, then the National Award. Suddenly everyone wanted to work with me. Those 3 years of rejection taught me everything.',
    advice: 'The film industry doesn\'t care about your degree. It cares about your stories. Write every day. Watch films obsessively. Be so persistent that the industry can\'t ignore you.',
    skills: ['Storytelling', 'Direction', 'Screenwriting', 'Team Management', 'Visual Thinking'],
    avatar: 'A',
    available: true,
    cluster: 'Media & Entertainment',
  },
  {
    id: '13',
    name: 'Deepa Krishnan',
    career: 'Chartered Accountant',
    company: 'Deloitte',
    experience: '7 years',
    city: 'Chennai',
    bio: 'Manager at Deloitte India specializing in M&A advisory. Handles deals worth 100+ crore regularly.',
    journey: 'Commerce stream from a regular school in Chennai. Started CA Foundation right after Class 12. Failed Intermediate Group 2 twice. Almost gave up. My study group kept me going. Cleared Final in first attempt. Joined a mid-size firm, then moved to Deloitte. CA is brutally hard but the skills you gain make you indispensable. I now advise companies on their biggest financial decisions.',
    advice: 'CA isn\'t about memorizing sections. It\'s about understanding how businesses work. If you can read a balance sheet like a story, you\'ll be great at this.',
    skills: ['Financial Analysis', 'Auditing', 'Tax Planning', 'M&A Advisory', 'Excel'],
    avatar: 'D',
    available: true,
    cluster: 'Finance & Commerce',
  },
  {
    id: '14',
    name: 'Siddharth Rao',
    career: 'Wildlife Conservationist',
    company: 'Wildlife Conservation Society',
    experience: '10 years',
    city: 'Dehradun',
    bio: 'Field biologist and conservationist working on tiger corridor protection in Central India. Has tracked 50+ individual tigers.',
    journey: 'BSc Zoology from Loyola College, Chennai. Did MSc Wildlife Biology from WII Dehradun. First job was counting pugmarks in 45-degree heat for Rs 15,000/month. Lived in forest camps for months without phone signal. Got charged by an elephant once. But waking up to tiger calls and knowing my work protects them? No office job compares. Now I lead conservation programs across 5 states.',
    advice: 'Conservation isn\'t glamorous Instagram posts. It\'s mud, mosquitoes, and patience. But if you love wild places, this career will fill your soul in ways nothing else can.',
    skills: ['Field Research', 'GIS Mapping', 'Community Engagement', 'Grant Writing', 'Data Analysis'],
    avatar: 'S',
    available: true,
    cluster: 'Science & Research',
  },
  {
    id: '15',
    name: 'Tanvi Bhatt',
    career: 'Game Developer',
    company: 'Ubisoft India',
    experience: '5 years',
    city: 'Pune',
    bio: 'Game programmer at Ubisoft working on AAA titles. Previously built indie games that got featured on Steam.',
    journey: 'BTech from COEP Pune. Was the only girl in my game dev club. Built 3 indie games during college, all terrible, but I learned everything from making them. Applied to Ubisoft 4 times before getting in. Started in QA, then moved to programming. Now I work on combat systems for games played by millions. Gaming is the most creative form of engineering.',
    advice: 'Don\'t just play games, make them. Download Unity or Unreal today and build something, even if it\'s just a ball bouncing. That\'s how every game developer started.',
    skills: ['C++', 'Unity', 'Unreal Engine', 'Game Design', 'Problem Solving'],
    avatar: 'T',
    available: true,
    cluster: 'Technology & AI',
  },
  {
    id: '16',
    name: 'Dr. Rahul Verma',
    career: 'Sports Psychologist',
    company: 'Sports Authority of India',
    experience: '8 years',
    city: 'Patiala',
    bio: 'Chief Sports Psychologist at SAI. Worked with Olympic athletes including medal winners. Specializes in performance anxiety and mental toughness.',
    journey: 'Was a decent cricketer in school, not good enough for professional play. Did BA Psychology, then MA Sports Psychology from Loughborough University, UK (scholarship). Came back to India when sports psychology barely existed here. Built the mental conditioning program at SAI from scratch. Helped 3 athletes through Olympic campaigns. The field is tiny but growing fast.',
    advice: 'The mind wins more medals than the body. If you love both sports and psychology, this is one of the most exciting and untapped careers in India.',
    skills: ['Performance Psychology', 'Counseling', 'Mental Conditioning', 'Data Analysis', 'Communication'],
    avatar: 'R',
    available: true,
    cluster: 'Sports & Fitness',
  },
  {
    id: '17',
    name: 'Niharika Jain',
    career: 'Investigative Journalist',
    company: 'The Indian Express',
    experience: '9 years',
    city: 'Delhi',
    bio: 'Senior investigative journalist who has broken multiple national-level stories on corruption and public interest issues.',
    journey: 'BA Mass Communication from Jamia. Started as an intern fetching tea and transcribing interviews. Got my first byline after 8 months. Spent years doing unglamorous local reporting before getting my first investigative assignment. The story took 6 months and required going undercover. It won a Ramnath Goenka Award. Journalism doesn\'t pay well, but the impact is unmatched.',
    advice: 'Journalism is about two things: curiosity and courage. If you\'re curious enough to dig and courageous enough to publish, the truth needs you.',
    skills: ['Investigative Research', 'Writing', 'Source Building', 'Data Analysis', 'Ethics'],
    avatar: 'N',
    available: true,
    cluster: 'Media & Entertainment',
  },
  {
    id: '18',
    name: 'Chef Imran Ali',
    career: 'Executive Chef',
    company: 'Masque Restaurant',
    experience: '12 years',
    city: 'Mumbai',
    bio: 'Executive chef specializing in modern Indian cuisine using local, seasonal ingredients. Trained at Le Cordon Bleu and worked in Michelin-starred kitchens in London.',
    journey: 'Family ran a small dhaba in Lucknow. Cooking was "beneath" a man according to relatives. Did hotel management from IHM Lucknow despite family objections. Won a scholarship to Le Cordon Bleu, Paris. Worked 16-hour days in London kitchens for 4 years. Came back to India because I wanted to elevate Indian food, not copy Western food. Now I run one of India\'s most celebrated restaurants.',
    advice: 'Cooking is the ultimate creative act — you make something from nothing and it brings people joy. But be ready for the hardest physical work of your life.',
    skills: ['Culinary Arts', 'Menu Development', 'Kitchen Management', 'Ingredient Sourcing', 'Food Science'],
    avatar: 'I',
    available: true,
    cluster: 'Hospitality & Food',
  },
  {
    id: '19',
    name: 'Lakshmi Sundaram',
    career: 'Social Worker & NGO Founder',
    company: 'Pratham Foundation',
    experience: '14 years',
    city: 'Pune',
    bio: 'Founded a nonprofit that has educated 50,000+ first-generation learners in rural Maharashtra. Ashoka Fellow and social entrepreneur.',
    journey: 'Grew up privileged in Pune. Did BA Sociology from Fergusson College. Went to a village for a college project and saw children who\'d never held a book. That trip changed my life. Did MSW from TISS Mumbai. Worked with Pratham for 3 years, then started my own initiative with zero funding. Begged, borrowed, and crowdfunded. 14 years later, we\'re in 200 villages. The pay is low but the purpose is infinite.',
    advice: 'If you want to make money, don\'t do social work. If you want to make meaning, there\'s nothing better. India needs a million social innovators.',
    skills: ['Community Organizing', 'Fundraising', 'Program Design', 'Advocacy', 'Team Leadership'],
    avatar: 'L',
    available: true,
    cluster: 'Social Impact',
  },
  {
    id: '20',
    name: 'Dr. Anand Bhaskar',
    career: 'Space Scientist',
    company: 'ISRO',
    experience: '16 years',
    city: 'Thiruvananthapuram',
    bio: 'Senior scientist at ISRO who worked on Chandrayaan-3 mission. Specializes in satellite propulsion systems.',
    journey: 'From a middle-class family in Thrissur, Kerala. Did BTech Aerospace from IIT Bombay. Could have gone to the US for a PhD but chose ISRO because I wanted to build India\'s space program. Spent years on unglamorous propulsion testing — standing in the rain watching rocket engines fire. Was part of the team when Chandrayaan-3 landed on the moon. That moment made 16 years of quiet work worth everything.',
    advice: 'Space is not just for geniuses. It\'s for persistent, detail-oriented people who can work in teams on very hard problems for very long times. If that excites you, look up.',
    skills: ['Aerospace Engineering', 'Propulsion Systems', 'MATLAB', 'Systems Engineering', 'Research'],
    avatar: 'A',
    available: true,
    cluster: 'Science & Research',
  },
];

export const mentorClusters = [
  ...new Set(mentors.map((m) => m.cluster)),
].sort();
