export interface Scholarship {
  id: string;
  name: string;
  provider: string;
  amount: string;
  eligibility: string;
  deadline?: string;
  streams: string[];
  link?: string;
  meritOrNeed: 'Merit' | 'Need' | 'Both';
}

export const scholarships: Scholarship[] = [
  {
    id: 'kvpy-fellowship',
    name: 'KVPY Fellowship',
    provider: 'Department of Science and Technology, Government of India',
    amount: 'Rs 5,000-7,000/month during BSc-MSc + annual contingency grant',
    eligibility: 'Class 11, 12, or 1st year BSc students with strong aptitude in basic sciences. Must qualify KVPY exam.',
    deadline: 'August (application), November (exam)',
    streams: ['Science'],
    link: 'https://kvpy.iisc.ac.in',
    meritOrNeed: 'Merit',
  },
  {
    id: 'inspire-scholarship',
    name: 'INSPIRE Scholarship (SHE)',
    provider: 'Department of Science and Technology, Government of India',
    amount: 'Rs 80,000/year for 5 years (BSc + MSc)',
    eligibility: 'Top 1% in Class 12 board exams pursuing BSc/BS/integrated MSc in natural sciences.',
    deadline: 'October-November',
    streams: ['Science'],
    link: 'https://online-inspire.gov.in',
    meritOrNeed: 'Merit',
  },
  {
    id: 'ntse-scholarship',
    name: 'NTSE Scholarship',
    provider: 'NCERT, Government of India',
    amount: 'Rs 1,250/month (Class 11-12), Rs 2,000/month (UG & PG)',
    eligibility: 'Class 10 students who qualify the two-stage NTSE examination.',
    deadline: 'August-September (registration)',
    streams: ['Science', 'Arts', 'Commerce'],
    link: 'https://ncert.nic.in/ntse.php',
    meritOrNeed: 'Merit',
  },
  {
    id: 'pm-scholarship-rpm',
    name: 'Prime Minister Scholarship Scheme (PMSS)',
    provider: 'Ministry of Defence, Government of India',
    amount: 'Rs 2,500/month (boys), Rs 3,000/month (girls) for professional courses',
    eligibility: 'Wards and widows of ex-servicemen/ex-coast guard personnel. Minimum 60% in Class 12.',
    deadline: 'October',
    streams: ['Engineering', 'Medical', 'Management', 'Law'],
    link: 'https://desw.gov.in',
    meritOrNeed: 'Both',
  },
  {
    id: 'aicte-pragati',
    name: 'AICTE Pragati Scholarship for Girls',
    provider: 'AICTE, Government of India',
    amount: 'Rs 50,000/year (up to 4 years)',
    eligibility: 'Girl students admitted to AICTE-approved institutions. Family income below Rs 8 lakh/year.',
    deadline: 'November-December',
    streams: ['Engineering', 'Management', 'Architecture'],
    link: 'https://www.aicte-india.org',
    meritOrNeed: 'Both',
  },
  {
    id: 'aicte-saksham',
    name: 'AICTE Saksham Scholarship',
    provider: 'AICTE, Government of India',
    amount: 'Rs 50,000/year (up to 4 years)',
    eligibility: 'Differently abled students in AICTE-approved technical institutions. Family income below Rs 8 lakh/year.',
    deadline: 'November-December',
    streams: ['Engineering', 'Management', 'Architecture'],
    link: 'https://www.aicte-india.org',
    meritOrNeed: 'Need',
  },
  {
    id: 'post-matric-sc',
    name: 'Post Matric Scholarship for SC Students',
    provider: 'Ministry of Social Justice and Empowerment, Government of India',
    amount: 'Full tuition fees + maintenance allowance (varies by course level)',
    eligibility: 'SC category students studying in Class 11 onwards. Family income below Rs 2.5 lakh/year.',
    deadline: 'Varies by state (July-October)',
    streams: ['Engineering', 'Medical', 'Arts', 'Science', 'Commerce', 'Law'],
    link: 'https://scholarships.gov.in',
    meritOrNeed: 'Need',
  },
  {
    id: 'post-matric-st',
    name: 'Post Matric Scholarship for ST Students',
    provider: 'Ministry of Tribal Affairs, Government of India',
    amount: 'Full tuition fees + maintenance allowance',
    eligibility: 'ST category students studying in Class 11 onwards. Family income below Rs 2.5 lakh/year.',
    deadline: 'Varies by state (July-October)',
    streams: ['Engineering', 'Medical', 'Arts', 'Science', 'Commerce', 'Law'],
    link: 'https://scholarships.gov.in',
    meritOrNeed: 'Need',
  },
  {
    id: 'post-matric-obc',
    name: 'Post Matric Scholarship for OBC Students',
    provider: 'Ministry of Social Justice and Empowerment, Government of India',
    amount: 'Tuition fees + maintenance allowance (varies)',
    eligibility: 'OBC category students in post-matriculation courses. Family income below Rs 1 lakh/year.',
    deadline: 'September-November',
    streams: ['Engineering', 'Medical', 'Arts', 'Science', 'Commerce', 'Law'],
    link: 'https://scholarships.gov.in',
    meritOrNeed: 'Need',
  },
  {
    id: 'minority-scholarship',
    name: 'Merit-cum-Means Scholarship for Minorities',
    provider: 'Ministry of Minority Affairs, Government of India',
    amount: 'Full tuition fee (up to Rs 20,000) + Rs 1,000/month maintenance',
    eligibility: 'Minority community students in professional and technical courses. Family income below Rs 2.5 lakh/year.',
    deadline: 'September-October',
    streams: ['Engineering', 'Medical', 'Management', 'Law'],
    link: 'https://scholarships.gov.in',
    meritOrNeed: 'Both',
  },
  {
    id: 'sitaram-jindal',
    name: 'Sitaram Jindal Foundation Scholarship',
    provider: 'Sitaram Jindal Foundation',
    amount: 'Rs 1,500-10,000/month depending on course level',
    eligibility: 'Students from economically weaker sections pursuing undergraduate, postgraduate, or professional courses.',
    deadline: 'Rolling admissions throughout the year',
    streams: ['Engineering', 'Medical', 'Arts', 'Science', 'Commerce', 'Law'],
    link: 'https://www.sitaramjindalfoundation.org',
    meritOrNeed: 'Need',
  },
  {
    id: 'tata-trusts-scholarship',
    name: 'Tata Trusts Scholarship',
    provider: 'Tata Trusts (various programs)',
    amount: 'Up to Rs 6 lakh/year for medical, Rs 2 lakh/year for engineering',
    eligibility: 'Meritorious students from economically weaker sections. Specific criteria vary by program.',
    deadline: 'July-September',
    streams: ['Medical', 'Engineering', 'Social Sciences'],
    link: 'https://www.tatatrusts.org',
    meritOrNeed: 'Both',
  },
  {
    id: 'azim-premji-scholarship',
    name: 'Azim Premji University Scholarship',
    provider: 'Azim Premji Foundation',
    amount: 'Up to 100% tuition fee waiver + living expenses',
    eligibility: 'Students admitted to Azim Premji University with demonstrated financial need.',
    deadline: 'At time of admission',
    streams: ['Education', 'Social Sciences', 'Engineering'],
    link: 'https://azimpremjiuniversity.edu.in',
    meritOrNeed: 'Need',
  },
  {
    id: 'narotam-sekhsaria',
    name: 'Narotam Sekhsaria Scholarship',
    provider: 'Narotam Sekhsaria Foundation',
    amount: 'Up to Rs 20 lakh (interest-free loan + scholarship component)',
    eligibility: 'Indian students pursuing postgraduate studies at top global and Indian universities. Strong academic record.',
    deadline: 'March',
    streams: ['Engineering', 'Management', 'Science', 'Arts', 'Social Sciences'],
    link: 'https://www.nsscholarship.org',
    meritOrNeed: 'Merit',
  },
  {
    id: 'jn-tata-endowment',
    name: 'JN Tata Endowment Loan Scholarship',
    provider: 'JN Tata Endowment for Higher Education',
    amount: 'Rs 1-10 lakh loan scholarship (partial gift, partial loan at 0% interest)',
    eligibility: 'Indian graduates admitted to top universities abroad for postgraduate studies.',
    deadline: 'March',
    streams: ['Engineering', 'Science', 'Management', 'Arts', 'Law', 'Social Sciences'],
    link: 'https://www.jntataendowment.org',
    meritOrNeed: 'Merit',
  },
  {
    id: 'ishan-uday',
    name: 'Ishan Uday Scholarship',
    provider: 'University Grants Commission (UGC)',
    amount: 'Rs 5,400/month (for engineering and medical), Rs 3,000/month (for others)',
    eligibility: 'Students from Northeast India pursuing higher education. Family income below Rs 4.5 lakh/year.',
    deadline: 'October-November',
    streams: ['Engineering', 'Medical', 'Arts', 'Science', 'Commerce'],
    link: 'https://www.ugc.gov.in',
    meritOrNeed: 'Need',
  },
  {
    id: 'central-sector-scholarship',
    name: 'Central Sector Scheme of Scholarships',
    provider: 'Ministry of Education, Government of India',
    amount: 'Rs 10,000/year (UG), Rs 20,000/year (PG), Rs 2,000/month (professional courses)',
    eligibility: 'Top 20 percentile in Class 12 board. Family income below Rs 8 lakh/year.',
    deadline: 'October-November',
    streams: ['Engineering', 'Medical', 'Arts', 'Science', 'Commerce', 'Law'],
    link: 'https://scholarships.gov.in',
    meritOrNeed: 'Both',
  },
  {
    id: 'nse-scholarship',
    name: 'NSE Academy Scholarship',
    provider: 'National Stock Exchange (NSE)',
    amount: 'Rs 10,000-50,000 per year',
    eligibility: 'Students pursuing finance, economics, or commerce courses. Merit-based selection.',
    deadline: 'August-September',
    streams: ['Commerce', 'Management'],
    link: 'https://www.nseindia.com',
    meritOrNeed: 'Merit',
  },
  {
    id: 'op-jindal-scholarship',
    name: 'O.P. Jindal Engineering & Management Scholarship',
    provider: 'O.P. Jindal Group',
    amount: 'Up to Rs 2.5 lakh/year',
    eligibility: 'Students admitted to top engineering and management institutions. Family income consideration.',
    deadline: 'September',
    streams: ['Engineering', 'Management'],
    link: 'https://www.opjgroup.com',
    meritOrNeed: 'Both',
  },
  {
    id: 'kishore-vaigyanik',
    name: 'DST INSPIRE Fellowship (Faculty)',
    provider: 'Department of Science and Technology',
    amount: 'Rs 25,000-35,000/month (PhD), Rs 80,000/month (Faculty)',
    eligibility: 'PhD students and early career faculty in science and engineering.',
    deadline: 'Rolling',
    streams: ['Science', 'Engineering'],
    link: 'https://online-inspire.gov.in',
    meritOrNeed: 'Merit',
  },
  {
    id: 'maulana-azad-fellowship',
    name: 'Maulana Azad National Fellowship',
    provider: 'Ministry of Minority Affairs',
    amount: 'Rs 31,000/month (JRF) for 2 years, Rs 35,000/month (SRF) for 3 years',
    eligibility: 'Minority students pursuing MPhil/PhD. Must have cleared NET/equivalent.',
    deadline: 'August-September',
    streams: ['Arts', 'Science', 'Commerce', 'Engineering'],
    link: 'https://www.ugc.gov.in',
    meritOrNeed: 'Both',
  },
  {
    id: 'swami-vivekananda-scholarship',
    name: 'Swami Vivekananda Merit-cum-Means Scholarship',
    provider: 'Government of West Bengal',
    amount: 'Rs 5,000-12,000/month based on course level',
    eligibility: 'Students from West Bengal with family income below Rs 2.5 lakh/year.',
    deadline: 'December-January',
    streams: ['Engineering', 'Medical', 'Science', 'Arts', 'Commerce'],
    link: 'https://svmcm.wbhed.gov.in',
    meritOrNeed: 'Both',
  },
  {
    id: 'vidyasiri-karnataka',
    name: 'Vidyasiri Scholarship (Karnataka)',
    provider: 'Government of Karnataka',
    amount: 'Rs 10,000-50,000/year based on course and category',
    eligibility: 'SC/ST/OBC students from Karnataka pursuing higher education. Income criteria apply.',
    deadline: 'September-October',
    streams: ['Engineering', 'Medical', 'Arts', 'Science', 'Commerce'],
    link: 'https://sw.kar.nic.in',
    meritOrNeed: 'Need',
  },
  {
    id: 'begum-hazrat-mahal',
    name: 'Begum Hazrat Mahal National Scholarship',
    provider: 'Maulana Azad Education Foundation, Ministry of Minority Affairs',
    amount: 'Rs 5,000 (Class 9-10), Rs 6,000 (Class 11-12)',
    eligibility: 'Meritorious girls from minority communities. Family income below Rs 2 lakh/year.',
    deadline: 'September-October',
    streams: ['Arts', 'Science', 'Commerce'],
    link: 'https://www.maef.nic.in',
    meritOrNeed: 'Both',
  },
  {
    id: 'reliance-foundation',
    name: 'Reliance Foundation Scholarship',
    provider: 'Reliance Foundation',
    amount: 'Up to Rs 2 lakh/year for UG, Rs 6 lakh/year for PG',
    eligibility: 'Students from economically weaker sections pursuing STEM, humanities, or social sciences.',
    deadline: 'June-July',
    streams: ['Engineering', 'Science', 'Arts', 'Social Sciences'],
    link: 'https://www.reliancefoundation.org',
    meritOrNeed: 'Both',
  },
  {
    id: 'kotak-kanya-scholarship',
    name: 'Kotak Kanya Scholarship',
    provider: 'Kotak Mahindra Group',
    amount: 'Up to Rs 1.5 lakh/year for professional courses',
    eligibility: 'Meritorious girl students from economically weaker sections. Family income below Rs 3.6 lakh/year. 12th marks above 85%.',
    deadline: 'August-September',
    streams: ['Engineering', 'Medical', 'Management', 'Science'],
    link: 'https://www.buddy4study.com/scholarship/kotak-kanya-scholarship',
    meritOrNeed: 'Both',
  },
  {
    id: 'hdfc-badhte-kadam',
    name: 'HDFC Bank Parivartan ECS Scholarship',
    provider: 'HDFC Bank',
    amount: 'Up to Rs 75,000/year',
    eligibility: 'Students from economically weaker sections. Family income below Rs 2.5 lakh/year.',
    deadline: 'August-September',
    streams: ['Engineering', 'Medical', 'Management', 'Arts', 'Science'],
    link: 'https://www.buddy4study.com/page/hdfc-bank-parivartan-ecs-scholarship',
    meritOrNeed: 'Need',
  },
  {
    id: 'ongc-scholarship',
    name: 'ONGC Scholarship for SC/ST Students',
    provider: 'Oil and Natural Gas Corporation',
    amount: 'Rs 48,000/year (engineering/medical), Rs 24,000/year (others)',
    eligibility: 'SC/ST students pursuing professional courses. Family income below Rs 2 lakh/year.',
    deadline: 'October',
    streams: ['Engineering', 'Medical', 'Management'],
    link: 'https://www.ongcindia.com',
    meritOrNeed: 'Need',
  },
  {
    id: 'ugc-net-jrf',
    name: 'UGC NET JRF Fellowship',
    provider: 'University Grants Commission',
    amount: 'Rs 31,000/month (JRF for 2 years), Rs 35,000/month (SRF for 3 years)',
    eligibility: 'Postgraduates who qualify UGC NET exam with JRF. Pursuing PhD in humanities, social sciences, science.',
    deadline: 'June and December (exam)',
    streams: ['Arts', 'Science', 'Commerce', 'Social Sciences'],
    link: 'https://ugcnet.nta.ac.in',
    meritOrNeed: 'Merit',
  },
  {
    id: 'fair-lovely-scholarship',
    name: 'STEM Scholarship by Glow & Lovely',
    provider: 'Hindustan Unilever / Glow & Lovely',
    amount: 'Up to Rs 2.5 lakh for professional courses',
    eligibility: 'Women students (18-30 years) pursuing professional courses. Family income below Rs 6 lakh/year.',
    deadline: 'March-April',
    streams: ['Engineering', 'Medical', 'Management', 'Science', 'Design'],
    link: 'https://www.buddy4study.com',
    meritOrNeed: 'Need',
  },
];

export const scholarshipStreams = [
  'Engineering', 'Medical', 'Science', 'Arts', 'Commerce', 'Management',
  'Law', 'Social Sciences', 'Design', 'Education', 'Architecture',
];
